<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/iLogos/logo_novafct.png" width="200">

# Departamento de Engenharia Mecânica e Industrial
## Mecânica Aplicada I 

## EQUILÍBRIO DO CORPO RÍGIDO NO PLANO. ATRITO.

### Problema 4 <a name="PIV"></a>

A figura representa duas massas $m_1$ e $m_2$ ligadas por um cabo passando em duas roldanas sem atrito A e B.  Sabe-se que a massa $m_1$ = 1500 kg e a massa $m_2$ = 500 kg. O coeficiente de atrito estático entre as massas $m_1$ e $m_2$ é $\mu_\textrm{e} = 0.3$, e entre a massa $m_1$ e a parede é $\mu_\textrm{e} = 0.5$.

[a)](#A) Trace separadamente os diagramas de corpo livre de cada uma das massas e de cada uma das roldanas.

[b)](#B) Determine a força mínima $\vec{F}$ que deverá estar aplicada para manter o sistema em equilíbrio. Determine ainda a correspondente força de tração no cabo.

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch03/P4/MAI_Ch03_P4.png"
width="200">

#### Revisão

O coeficiente de atrito é uma quantidade adimensional que expressa a oposição que exercem as superfícies (rugosas) de dois corpos em contato ao deslizar um em relação ao outro.

O valor do coeficiente de atrito é caraterístico de cada par de materiais, e não sendo portanto uma propriedade intrínseca do material. Depende de muitos fatores tais como o acabamento das superfícies em contato, a velocidade relativa entre as superfícies, a temperatura, etc.

Geralmente distinguem-se dois valores:

- Coeficiente de atrito estático ($\mu_\textrm{e}$): é medido quando ambas as superfícies estão em repouso (sem se mover).

- Coeficiente de atrito cinético ($\mu_\textrm{c}$): é medido quando uma ou ambas as superfícies estão em movimento.



### Resolução

#### a) Trace separadamente os diagramas de corpo livre de cada uma das massas e de cada uma das roldanas. <a id="A"></a> ([enunciatum](#PIV))

**O DCL da roldana A**

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch03/P4/MAI_Ch03_P4a.jpg"
width="250">

Do somatório de forças verticais, pode-se escrever que

\begin{equation*}
R_A = 2 F_{T_1}
\end{equation*}

**O DCL da roldana B**

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch03/P4/MAI_Ch03_P4b.jpg"
width="250">

Do somatório de forças verticais, pode-se escrever que:

\begin{equation*}
F_{T_2} = 2 F_{T_1}
\end{equation*}

**O DCL da caixa de massa $m_1$**

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch03/P4/MAI_Ch03_P4c.jpg"
width="250">

Com um peso de:

\begin{equation*}
P_1 = m_1 g
\end{equation*}

In [2]:
m1 = 1500 # unit: kg
g = 9.81 # unit: m/s^2

P1 = m1*g
print('P1 = ','{:.1f}'.format(P1),' N')

P1 =  14715.0  N


**O DCL da caixa de massa $m_2$**

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MAI/Notebooks/Ch03/P4/MAI_Ch03_P4d.jpg"
width="250">

Com um peso de:

\begin{equation*}
P_2 = m_2 g
\end{equation*}

In [3]:
m2 = 500 # unit: kg
P2 = m2*g
print('P2 = ','{:.1f}'.format(P2),' N')

P2 =  4905.0  N


#### b) Determine a força mínima $\vec{F}$ que deverá estar aplicada para manter o sistema em equilíbrio.  Determine ainda a correspondente força de tração no cabo. <a id="B"></a> ([enunciatum](#PIV))

**Massa $\mathbf{m_2}$ :**

Do equilíbrio das forças envolvidas no diagrama de corpo livre da massa $m_2$ resulta:

\begin{equation*}
\vec{R}=\sum_{i}\vec{F}_i = 0
~\Leftrightarrow~
\begin{cases}
\sum  F_\textrm{x} = 0 \\
\sum F_\textrm{y} = 0
\end{cases}
~\Leftrightarrow~
\begin{cases}
F - F_\textrm{N1} = 0 \\
-m_2g - F_\textrm{A1} + F_\textrm{T1} = 0
\end{cases}
\end{equation*}

com $F_\textrm{A1} = \mu_\textrm{e} F_\textrm{N1}$ e $\mu_\textrm{e} = 0.3$,

\begin{equation*}
\begin{cases}
\sum  F_\textrm{x} = 0 \\
\sum F_\textrm{y} = 0
\end{cases}
~\Leftrightarrow~
\begin{cases}
F - F_\textrm{N1} = 0 \\
-m_2g - 0.3F_\textrm{N1} + F_\textrm{T1} = 0
\end{cases}
\end{equation*}

In [4]:
import sympy as sy
from sympy.solvers import solve

mu12 = 0.3
mu20 = 0.5

f, fn1, ft1 = sy.symbols('f fn1 ft1')

sumFx_2 = f - fn1
print('sumFx (m2) = ',sumFx_2)
sumFy_2 = -P2 - mu12*fn1 + ft1
print('sumFy (m2) = ',sumFy_2)

sumFx (m2) =  f - fn1
sumFy (m2) =  -0.3*fn1 + ft1 - 4905.0


**Massa $\mathbf{m_1}$ :**

Do equilíbrio das forças envolvidas no diagrama de corpo livre da massa $m_1$ vem:

\begin{equation*}
\begin{cases}
\sum  F_\textrm{x} = 0 \\
\sum F_\textrm{y} = 0
\end{cases}
~\Leftrightarrow~
\begin{cases}
F_\textrm{N1} - F_\textrm{N2} = 0 \\
-m_1g + F_\textrm{A1} + F_\textrm{A2} + F_\textrm{T2} = 0
\end{cases}
\end{equation*}

com $F_\textrm{A1} = 0.3 F_\textrm{N1}~(\mu_\textrm{e}=0.3)$, $F_\textrm{A2} =
0.5 F_\textrm{N2}~(\mu_\textrm{e}=0.5)$ e $F_\textrm{T2} = 2F_\textrm{T1}$
(do equilíbrio da roldana B),

\begin{equation*}
\begin{cases}
\sum  F_\textrm{x} = 0 \\
\sum F_\textrm{y} = 0
\end{cases}
~\Leftrightarrow~
\begin{cases}
F_\textrm{N1} - F_\textrm{N2}= 0 \\
-m_1g + 0.3F_\textrm{N1} + 0.5F_\textrm{N2} + 2F_\textrm{T1} = 0
\end{cases}
\end{equation*}

In [5]:
fn2, ft2 = sy.symbols('fn2 ft2')

sumFx_1 = fn1 - fn2
print('sumFx (m1) = ',sumFx_1)
sumFy_1 = -P1 + mu12*fn1 + mu20*fn2 + 2*ft1
print('sumFy (m1) = ',sumFy_1)

sumFx (m1) =  fn1 - fn2
sumFy (m1) =  0.3*fn1 + 0.5*fn2 + 2*ft1 - 14715.0


**Sistema de equações**

Agrupando as equações de equilíbrio têm-se:

\begin{equation*}
\begin{cases}
F - F_\textrm{N1} = 0 \\
- 0.3F_\textrm{N1} + F_\textrm{T1} = m_2g \\
F_\textrm{N1} - F_\textrm{N2}= 0 \\
0.3F_\textrm{N1} + 0.5F_\textrm{N2} + 2F_\textrm{T1} = m_1g 
\end{cases}
\end{equation*}

In [6]:
sol = solve({sumFx_2,sumFy_2,sumFx_1,sumFy_1},{f, fn1, ft1, fn2})
print('Sistema de equações --------------------')
F = sol[f]
print('F   = ','{:.1f}'.format(F),' N')
FN1 = sol[fn1]
print('FN1 = ','{:.1f}'.format(FN1),' N')
FN2 = sol[fn2]
print('FN2 = ','{:.1f}'.format(FN2),' N')
FT1 = sol[ft1]
print('FT1 = ','{:.1f}'.format(FT1),' N')

print('\nOutras variáveis --------------------')
FA1 = mu12*FN1
print('FA1 = ','{:.1f}'.format(FA1),' N')
FA2 = mu20*FN2
print('FA2 = ','{:.1f}'.format(FA2),' N')
FT2 = 2*FT1
print('FT2 = ','{:.1f}'.format(FT2),' N')

Sistema de equações --------------------
F   =  3503.6  N
FN1 =  3503.6  N
FN2 =  3503.6  N
FT1 =  5956.1  N

Outras variáveis --------------------
FA1 =  1051.1  N
FA2 =  1751.8  N
FT2 =  11912.1  N


Numa resolução alternativa na forma matricial pode-se resolver:

\begin{equation*}
[A]\{x\}=\{b\} \Leftrightarrow
\begin{bmatrix}
1 & -1 & 0 & 0 \\
0 & -0.3 & 0 & 1 \\
0 & 0.3 & 0.5 & 2 \\
0 & 1 & 0 & -1
\end{bmatrix}
\begin{bmatrix}
F \\ F_\textrm{N1} \\ F_\textrm{N2} \\ F_\textrm{T1}
\end{bmatrix}=
\begin{bmatrix}
0 \\ m_2g \\ 0 \\ m_1g
\end{bmatrix}
\end{equation*}

cuja solução é: $\{x\}=[A]^{-1}\{b\}$

In [7]:
import numpy as np
np. set_printoptions(precision=1, suppress=True)

A0 = [1, -1, 0, 0]
A1 = [0, -0.3, 0, 1]
A2 = [0, 1, -1, 0]
A3 = [0, 0.3, 0.5, 2]

A = np.array([A0,A1,A2,A3])
print(f'A =\n {A}')

invA = np.linalg.inv(A)
print(f'A^-1 =\n {invA}')

b = np.array([0,P2,0,P1])
print(f'b = {b}')

A =
 [[ 1.  -1.   0.   0. ]
 [ 0.  -0.3  0.   1. ]
 [ 0.   1.  -1.   0. ]
 [ 0.   0.3  0.5  2. ]]
A^-1 =
 [[ 1.  -1.4  0.4  0.7]
 [ 0.  -1.4  0.4  0.7]
 [ 0.  -1.4 -0.6  0.7]
 [ 0.   0.6  0.1  0.2]]
b = [    0.  4905.     0. 14715.]


In [8]:
print('Solução --------------------')
x = np.linalg.solve(A,b)
print(f'x = {x} [N]')
print(f'F = FN1 = FN2 = {x[0]:.1f} N')
print(f'FT1 = {x[3]:.1f} N')
print('+ outras forças ------------')
print(f'FA1 = {x[1]*mu12:.1f} N')
print(f'FA2 = {x[2]*mu20:.1f} N')
print(f'FT2 = {x[3]*2:.1f} N')

Solução --------------------
x = [3503.6 3503.6 3503.6 5956.1] [N]
F = FN1 = FN2 = 3503.6 N
FT1 = 5956.1 N
+ outras forças ------------
FA1 = 1051.1 N
FA2 = 1751.8 N
FT2 = 11912.1 N


---

Copyright (c) DEMI - FCT NOVA

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>