<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/iLogos/nsst.jpg" width="400" height="100">

# DEMI | NOVA SST

## Mecânica dos Sólidos I

# I.1 Conceito de tensão. Vector tensão. Tensão normal e tangencial. Equações de equilíbrio e tensor das tensões.

## Problema 3 <a name="PI13"></a>

Considere o estado de tensão no ponto $m$ definido por (kPa):

\begin{equation*}
\begin{cases}
\sigma_{xx} = 800 \quad \sigma_{yy} = -5000 \quad \sigma_{zz} = 0 \\
\sigma_{xy} = 100 \quad \sigma_{xz} = 0 \quad \sigma_{yz} = –300
\end{cases}
\end{equation*}

a) Determine as componentes do vector tensão num plano cuja normal é dada por $\vec{m} = 3\vec{i} + 6\vec{j} + 12\vec{k}$.

b) Obtenha a componente da tensão na mesma direcção e a componente tangencial no plano considerado.



## Resolução

#### a) Determine as componentes do vector tensão num plano cuja normal é dada por $\vec{m} = 3\vec{i} + 6\vec{j} + 12\vec{k}$.

A partir dos valores enunciados das componentes do tensor das tensões num determinado sistema de coordenadas ortonormado, pode-se constuir diretamente a matriz que representa esse estado de tenão no ponto, $\sigma_{ij}(m)$:

\begin{equation*}
\sigma_{ij} =
\begin{bmatrix}
\sigma_{11} & \sigma_{12} & \sigma_{13} \\
\sigma_{21}(=\sigma_{12}) & \sigma_{22} & \sigma_{23} \\
\sigma_{31}(=\sigma_{13}) & \sigma_{32}(=\sigma_{23}) & \sigma_{33}
\end{bmatrix} =
\begin{bmatrix}
\sigma_{11} & \tau_{12} & \tau_{13} \\
\tau_{21} & \sigma_{22} & \tau_{23} \\
\tau_{31} & \tau_{32} & \sigma_{33}
\end{bmatrix}
\end{equation*}

As componentes cartesianas do vetor tensão, que atua no ponto $M$ e sobre uma faceta cuja orientação é definida pelo versor que lhe é perpendicular, $\vec{n} \equiv \hat{n}$, é dado pela fórmula das tensões de Cauchy:

\begin{equation*}
\begin{aligned}
t_i & = \sigma_{ji} \cdot n_{j} \quad &\textrm{(notação indicial)} \\
\vec{t}{(\vec{x},\vec{n},t)} & = \tilde{\sigma}^T{(\vec{x},\vec{n},t)} \cdot
\vec{n} \quad &\textrm{(notação tensorial)} \\
\underline{t}{(\vec{x},\vec{n},t)} & =
\underline{\underline{\sigma}}^T{(\vec{x},t)}\cdot\vec{n}
\quad &\textrm{
(notação matricial)} \\
\end{aligned}
\end{equation*}

Desenvolvendo algebricamente têm-se a seguite expressão matricial,

\begin{equation*}
\begin{bmatrix}
t_1 \\ t_2 \\ t_3
\end{bmatrix} =
\begin{bmatrix}
\sigma_{11} & \sigma_{21} & \sigma_{31} \\
\sigma_{12} & \sigma_{22} & \sigma_{32} \\
\sigma_{13} & \sigma_{23} & \sigma_{33}
\end{bmatrix}
\begin{bmatrix}
n_1 \\ n_2 \\ n_3
\end{bmatrix}
\end{equation*}

O versor $\vec{n}$ que define a direção do vetor $\vec{m} = m_1\vec{i} + m_2\vec{j} + m_3\vec{k} = 3\vec{i} + 6\vec{j} + 12\vec{k}$ pode ser obtido pela seguinte normalização:

\begin{equation*}
\vec{n} = \frac{\vec{m}}{||\vec{m}||_2} \quad\textrm{com}\quad
||\vec{m}||_2 = (m_1^2 + m_2^2 + m_3^2)^{1/2}
\end{equation*}

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def vetor(n1,n2,n3):
    return np.array([n1, n2, n3])

def TensorTensoes(s11,s12,s13,s21,s22,s23,s31,s32,s33):
    return np.array([[s11,s12,s13], [s21,s22,s23], [s31,s32,s33]])

# determinação do versor que defini o vetor n dado
vetor_n = vetor(3, 6, 12)
versor_n_norm = np.sqrt(vetor_n[0]**2 + vetor_n[1]**2 + vetor_n[2]**2)
versor_n = vetor_n/versor_n_norm

print('I. norma do vetor m = ','{:.3f}'.format(versor_n_norm))

print("II. versor normal à faceta no ponto p - m/||m|| :")
print('versor (n) = ','{:.3f}'.format(versor_n[0]),' i + ',\
      '{:.3f}'.format(versor_n[1]),' j + ',\
      '{:.3f}'.format(versor_n[2]),' k')
print('verificao: || n || = ','{:.3f}'.format(np.linalg.norm(versor_n)))

I. norma do vetor m =  13.748
II. versor normal à faceta no ponto p - m/||m|| :
versor (n) =  0.218  i +  0.436  j +  0.873  k
verificao: || n || =  1.000


In [2]:
Sigma_n = TensorTensoes(800, 100, 0, 100, -5000, -300, 0, -300, 0)
vetor_tensao_n = np.dot(versor_n,Sigma_n)

print("III. O tensor das tensões é dado por (kPa):")
print(Sigma_n)

III. O tensor das tensões é dado por (kPa):
[[  800   100     0]
 [  100 -5000  -300]
 [    0  -300     0]]


In [3]:
np.set_printoptions(precision=1)
print("VI. O vetor tensão no ponto P num plano perpendicular \
ao versor (3, 6, 12) é :")
print("t^n = ",vetor_tensao_n, "kPa")

VI. O vetor tensão no ponto P num plano perpendicular ao versor (3, 6, 12) é :
t^n =  [  218.2 -2422.2  -130.9] kPa


#### b) Obtenha a componente da tensão na mesma direcção e a componente tangencial no plano considerado.

Considere-se uma partícula no interior dum corpo deformável. Seja $p$ o ponto que essa partícula ocupa na configuração atual $O(t)$, após solicitação externa, definida pelo vetor posição $\vec{x}$. Seja $\vec{n}$ o versor que define a orientação (normal) de uma faceta que contem o ponto $p$. A direção do vetor de tensão, $\vec{t} (\vec{x}, \vec{n},t)$, que atua no ponto $p$ e na faceta $\vec{n}$, não coincide geralmente com a direção definida pelo versor normal à faceta onde atua ($\vec{n}$), nem com a direção tangente à faceta (ortogonal a $\vec{n}$). Assim sendo, é possível decompor $\vec{t}(\vec{x},\vec{n},t)$ numa componente com a direção de $\vec{n}$ e numa componente perpendicular a $\vec{n}$:

\begin{equation*}
    \vec{t}(\vec{x},\vec{n},t) = \vec{\sigma}(\vec{x},\vec{n},t) + \vec{\tau}(\vec{x},\vec{n},t)
\end{equation*}

com,

\begin{equation*}
    \vec{\sigma} \cdot \vec{\tau} = 0
\end{equation*}

A componente $\vec{\sigma}$ designa-se tensão normal e a componente $\vec{\tau}$ chama-se tensão de corte, no ponto $p$ e para a direção $\vec{n}$.

A tensão normal pode ser obtida pelo produto interno dos vetores de $\vec{t}(\vec{x},\vec{n},t)$ por $\vec{n}$. Em notação indicial escreve-se:

\begin{equation*}
\sigma = t_i \cdot n_i
\end{equation*}

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/Notebooks/Au01/Au01_P003_i1.jpg" width="250" height="200">

In [4]:
tensao_normal = np.dot(vetor_tensao_n,versor_n)
print("A componente de tensão normal é: ",'{:.2f}'.format(tensao_normal), "kPa")

A componente de tensão normal é:  -1123.81 kPa


A norma da tensão tangencial pode ser calculada pelo teorema de Pitágoras:

\begin{equation*}
||\vec{t}(\vec{x},\vec{n})||^2 = \sigma^2 + \tau^2
\end{equation*}

pelo que,

\begin{equation*}
\tau = \sqrt{\vec{t} \cdot \vec{t} - \sigma^2}
\end{equation*}

In [5]:
vt_n2 = np.dot(vetor_tensao_n,vetor_tensao_n)
tensao_tangencial = np.sqrt(vt_n2 - tensao_normal**2)
print(f"A componente da tensão tangencial é: {tensao_tangencial:.2f} kPa")

A componente da tensão tangencial é: 2160.78 kPa


---

Copyright (c) [Mecânica dos Sólidos I - DEMI - NOVA-SST]

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>
