<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/iLogos/nsst.jpg" width="400" height="100">

# DEMI | NOVA SST

## Mecânica dos Sólidos I

# I.2 Transformação de tensões. Tensões principais. Direções principais.

## Problema 2 <a name="PI22"></a>

Considere três planos diferentes passando por um ponto $P$ no interior de um
objeto, cujas normais e respectivos vetores tensão (MPa) são dados por:

\begin{equation*}
\begin{aligned}
\vec{n}_1 &= \sqrt{3}/2 \vec{\imath}~+~1/2~\vec{k} \qquad &
\vec{t}{(\vec{n}_1)} &= 5\sqrt{3}\vec{\imath}~+\sqrt{3}\vec{\jmath}~-~5/2\vec{k}\\
\vec{n}_2 &= \vec{\jmath} \qquad  &
\vec{t}{(\vec{n}_2)} &= 2\vec{\imath}~+5\vec{\jmath}\\
\vec{n}_3 &= -1/2 \vec{\imath}~+~\sqrt{3}/2\vec{k} \qquad &
\vec{t}{(\vec{n}_3)} &= -5\vec{\imath}~-\vec{\jmath}~-~(5\sqrt{3})/2\vec{k}\\
\end{aligned}
\end{equation*}

[a)](#A) Prove que estes três vectores de tensão são suficientes para definir completamente o estado de tensão no ponto $P$.

[b)](#B) Calcule o tensor das tensões no referencial definido pelos versores ($\vec{\imath}, \vec{\jmath}, \vec{k}$).

[c)](#C) Calcule as componentes normal e tangencial do vector tensão associado ao plano cuja normal faz
ângulos iguais com $(\vec{\imath}, \vec{\jmath}, \vec{k})$.

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/Notebooks/Au02/Au02_P002_infografico.jpg"
width="600" height="350">


## Resolução

#### a) Prove que estes três vectores de tensão são suficientes para definir completamente o estado de tensão no ponto $P$.<a name="A"></a>
([enunciatum](#PI22))

Os três vetores de tensão $\vec{t}{(\vec{n}_i)}$ ($i=1,2,3$) são necessários e suficientes para definir completamente o estado de tensão num ponto $P$ no interior de um objeto, se os três vetores estiverem aplicados em três planos ortogonais entre si, e cujas normais formam um sistema de coordenadas ortonormado (i.e. eixos perpendiculares, cujas escalas têm a mesma dimensão) e direto (i.e. $\vec{k} = \vec{\imath} \times \vec{\jmath}$). Esta condição pode ser analisada a partir dos versores que definem os eixos perpendiculares às facetas onde atuam as tensões no ponto.

Os vetores de base $\vec{e}_i$ formam um sistema de coordenadas ortonormal se verificarem os seguintes produtos escalares:

\begin{equation*}
\vec{e}_i \cdot \vec{e}_j = \delta_{ij}~;\quad
\delta_{ij} =
\begin{cases}
1 \quad \textrm{para}\quad i = j \\
0 \quad \textrm{para}\quad i \ne j
\end{cases}
\end{equation*}

(Em algebra linear, dois vetores  de um espaço vetorial de produto interno são ortonormais se forem vetores ortogonais e unitários.):

In [1]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

def versor(v1,v2,v3): return np.array([v1,v2,v3])

n1 = versor(np.sqrt(3)/2,0,1/2)
n2 = versor(0,1,0)
n3 = versor(-1/2,0,np.sqrt(3)/2)

print('n1 = ',n1)
print('n2 = ',n2)
print('n3 = ',n3)

n1 =  [ 0.866  0.000  0.500]
n2 =  [0 1 0]
n3 =  [-0.500  0.000  0.866]


In [2]:
print('i = j: ')
print(f'np.dot(n1,n1) = {np.dot(n1,n1):.1f}')
print(f'np.dot(n2,n2) = {np.dot(n2,n2):.1f}')
print(f'np.dot(n3,n3) = {np.dot(n3,n3):.1f}')

i = j: 
np.dot(n1,n1) = 1.0
np.dot(n2,n2) = 1.0
np.dot(n3,n3) = 1.0


In [3]:
print('i ne j: ')
print(f'np.dot(n2,n3) = {np.dot(n2,n3):.1f}')
print(f'np.dot(n1,n3) = {np.dot(n1,n3):.1f}')
print(f'np.dot(n1,n2) = {np.dot(n1,n2):.1f}')

i ne j: 
np.dot(n2,n3) = 0.0
np.dot(n1,n3) = 0.0
np.dot(n1,n2) = 0.0


Além disso, a base $\vec{e}_i$ forma um sistema de coordenadas direto ou inverso se verificar, respetivamente:

\begin{equation*}
\vec{e}_1 \cdot (\vec{e}_2 \times \vec{e}_3) = 1~\textrm{(direto)};
\qquad
\vec{e}_1 \cdot (\vec{e}_2 \times \vec{e}_3) = -1~\textrm{(inverso)}
\end{equation*}

In [4]:
from sympy.physics.mechanics import ReferenceFrame, cross, dot

S = ReferenceFrame('S') # ||x|| = ||y|| = ||z|| = 1
syn1 = n1[0]*S.x + n1[1]*S.y + n1[2]*S.z; print(f'vec n1 : {syn1}')
syn2 = n2[0]*S.x + n2[1]*S.y + n2[2]*S.z; print(f'vec n2 : {syn2}')
syn3 = n3[0]*S.x + n3[1]*S.y + n3[2]*S.z; print(f'vec n3 : {syn3}')

basedir = dot(syn1,cross(syn2,syn3))
print(f'\nbase direta = {basedir:.1f}')

vec n1 : 0.866025403784439*S.x + 0.5*S.z
vec n2 : S.y
vec n3 : - 0.5*S.x + 0.866025403784439*S.z

base direta = 1.0


Finalmnete, a base $\vec{e}_i$ deve verificar a convenção da regra da mão direita:

\begin{equation*}
\vec{e}_i \times \vec{e}_j = \epsilon_{ijk}~\vec{e}_k;\quad
\epsilon_{ijk} =
\begin{cases}
0 \quad \textrm{se $(ijk)$ forem todos iguais}\\
1 \quad \textrm{se $(ijk)$ for uma permutação par: i.e. 123,231,
231}\\
-1 \quad \textrm{se $(ijk)$ for uma permutação ímpar: i.e. 213,321,
131}
\end{cases}
\end{equation*}

Segundo a convensão da regra da mão, por exemplo, verifica-se neste caso:

\begin{equation*}
\vec{n}_1 \times \vec{n}_2 = \vec{n}_3~; \quad
\vec{n}_2 \times \vec{n}_3 = \vec{n}_1~; \quad
\vec{n}_3 \times \vec{n}_1 = \vec{n}_2
\end{equation*}

In [5]:

CP123 = cross(syn1,syn2); print('Cross n1 x n2 = n3: ',CP123)
CP231 = cross(syn2,syn3); print('Cross n2 x n3 = n1: ',CP231)
CP312 = cross(syn3,syn1); print('Cross n3 x n1 = n2: ',CP312)

Cross n1 x n2 = n3:  - 0.5*S.x + 0.866025403784439*S.z
Cross n2 x n3 = n1:  0.866025403784439*S.x + 0.5*S.z
Cross n3 x n1 = n2:  1.0*S.y


Verifica-se que os versores definem um sistema de coordenadas ortonormal e direto.

#### b) Calcule o tensor das tensões no referencial definido pelos versores ($\vec{\imath}, \vec{\jmath}, \vec{k}$).<a name="B"></a>
([enunciatum](#PI22))

**Mudança de base para o vetor tensão**

Considerem-se dois sistemas de coordenadas $S_0(0,\vec{\imath},\vec{\jmath},\vec{k})\equiv S_0(0,\vec{\imath}_0,\vec{\jmath}_0,\vec{k}_0)$ e $S_1(0,\vec{n}_1,\vec{n}_2,\vec{n}_3)\equiv S_1(0,\vec{\imath}_1,\vec{\jmath}_1,\vec{k}_1)$, com a mesma origem mas orientações distintas.

As componentes do vetor de tensão $\vec{t}{(\vec{n})}$ nos sistemas de coordenadas $S_0$ e $S_1$ estão relacionadas através da seguinte transformação:

\begin{equation*}
\underline{t}_1 = \underline{\underline{T}}_{0/1}\cdot\underline{t}_0
\quad\quad\textrm{ou}\quad\quad
\underline{t}_0 = \underline{\underline{T}}_{1/0}\cdot\underline{t}_1
\end{equation*}

em que $\underline{\underline{T}}_{0/1}$ é a matriz ortogonal da mudança de base de $S_0$ em $S_1$ e $\underline{\underline{T}}_{1/0}$ é a matriz de transformação de $S_1$ em $S_2$, respetivamente.

A matriz de mudança de base representando a transformação do sistema de coordenadas $S_0(\vec{\imath},\vec{\jmath},\vec{k})$ em $S_1(0,\vec{n}_1,\vec{n}_2,\vec{n}_3)$, é assim definida (Apêndice A):

\begin{equation*}
\underline{\underline{T}}_{0/1} =
\begin{bmatrix}
\vec{\imath} \cdot \vec{n}_1 & \vec{\jmath}\cdot\vec{n}_1 & \vec{k}\cdot\vec{n}_1 \\
\vec{\imath} \cdot \vec{n}_2 & \vec{\jmath}\cdot\vec{n}_2 & \vec{k}\cdot\vec{n}_2\\
\vec{\imath} \cdot \vec{n}_3 & \vec{\jmath}\cdot\vec{n}_3 & \vec{k}\cdot\vec{n}_3
\end{bmatrix}
=
\begin{bmatrix}
\cos(\vec{\imath},\vec{n}_1) & \cos(\vec{\jmath},\vec{n}_1) & \cos(\vec{k},\vec{n}_1) \\
\cos(\vec{\imath},\vec{n}_2) & \cos(\vec{\jmath},\vec{n}_2) & \cos(\vec{k},\vec{n}_2) \\
\cos(\vec{\imath},\vec{n}_3) & \cos(\vec{\jmath},\vec{n}_3) & \cos(\vec{k},\vec{n}_3) \\
\end{bmatrix}
\end{equation*}

desenvolvendo,

\begin{equation*}
\underline{\underline{T}}_{0/1} =
\begin{bmatrix}
\sqrt{3}/2 & 0 & 1/2 \\
0 & 1 & 0 \\
-1/2 & 0 & \sqrt{3}/2 \\
\end{bmatrix} =
\begin{bmatrix}
\vec{n}_1^T \\
\vec{n}_2^T \\
\vec{n}_3^T \\
\end{bmatrix}
\end{equation*}


por outras palavras, as linhas da matriz $[T]_{0/1}$ são os cosenos diretores de cada versor da nova base ($\vec{n}_1,\vec{n}_2,\vec{n}_3$) em relação aos eixos do referencial original ($\vec{\imath},\vec{\jmath},\vec{k}$).

In [6]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

def trans01(i0i1,i0j1,i0k1,j0i1,j0j1,j0k1,k0i1,k0j1,k0k1):
    linha0 = [i0i1,j0i1,k0i1]
    linha1 = [i0j1,j0j1,k0j1]
    linha2 = [i0k1,j0k1,k0k1]
    return np.array([linha0,linha1,linha2])

Q01 = trans01(n1[0],n2[0],n3[0],n1[1],n2[1],n3[1],n1[2],n2[2],n3[2])
print(f'\n Matriz de mudanca de base de S0 para S1: \n T01 = \n {Q01}')


 Matriz de mudanca de base de S0 para S1: 
 T01 = 
 [[ 0.866  0.000  0.500]
 [ 0.000  1.000  0.000]
 [-0.500  0.000  0.866]]


In [7]:
print('[T01^T][T01] = [I] = \n',np.dot(np.transpose(Q01),Q01))
print('\n det([T01]) = ','{: 0.1f}'.format(np.linalg.det(Q01)))

[T01^T][T01] = [I] = 
 [[ 1.000  0.000  0.000]
 [ 0.000  1.000  0.000]
 [ 0.000  0.000  1.000]]

 det([T01]) =   1.0


**Mudança de base para a matriz das tensões**

A matriz das tensões, $[\sigma]$, num ponto de um meio contínuo contem as componentes dos vetores de tensão que atuam em três facetas (ou planos) cujas normais definem um dado sistema de coordenadas ortonormado e direto. Por esse motivo, a definição desta matriz exige a escolha prévia de um referêncial.

No sistema de coordenadas $S_0(0,\vec{\imath}_0,\vec{\jmath}_0,\vec{k}_0)$, a  matriz das tensões no ponto genérico $P$ é dada por:

\begin{equation*}
^0\underline{\underline{\sigma}} =
\begin{bmatrix}
\sigma_{xx} & \tau_{xy} & \tau_{xz} \\
\tau_{xy} & \sigma_{yy} & \tau_{yz} \\
\tau_{xz} & \tau_{yz} & \sigma_{zz}
\end{bmatrix}
\end{equation*}

Noutro sistema de coodenadas, $S_1(0,\vec{\imath}_1,\vec{\jmath}_1,\vec{k}_1)$, a matriz das tensões vem dada por:

\begin{equation*}
^1\underline{\underline{\sigma}} =
\begin{bmatrix}
\sigma_{x'x'} & \tau_{x'y'} & \tau_{x'z'} \\
\tau_{x'y'} & \sigma_{y'y'} & \tau_{y'z'} \\
\tau_{x'z'} & \tau_{y'z'} & \sigma_{z'z'}
\end{bmatrix}
\end{equation*}

Considere-se o seguinte desenvolvimento da fórmula de Cauchy do sistema de coordenadas $S_0$ para $S_1$:

\begin{equation*}
\begin{aligned}
\underline{t}_0\,&=\,\underline{\underline{\sigma}}_0\cdot\!\underline{n}_0\\
\Leftrightarrow~\underline{\underline{T}}_{1/0}\cdot\!\underline{t}_1&=\,\underline{\underline{\sigma}}_0~
\underline{\underline{T}}_{1/0}\cdot\!\underline{n}_1 \\
\Leftrightarrow~\underline{t}_1&=\underline{\underline{T}}_{1/0}^T\,\underline{\underline{\sigma}}_0~
\underline{\underline{T}}_{1/0}\cdot\!\underline{n}_1 \\
\Leftrightarrow~\underline{t}_1&=\underline{\underline{T}}_{0/1}\,\underline{\underline{\sigma}}_0~
\underline{\underline{T}}_{0/1}^T\cdot\!\underline{n}_1 \\
\Leftrightarrow~\underline{t}_1&=\,\underline{\underline{\sigma}}_1\cdot\!\underline{n}_1
\end{aligned}
\end{equation*}

Chega-se portanto à seguinte lei de transformação da matriz das tensões numa mudança de base ortogonal:

\begin{equation*}
\begin{aligned}
\underline{\underline{\sigma}}_1&=\underline{\underline{T}}_{0/1}\,\underline{\underline{\sigma}}_0~
\underline{\underline{T}}_{0/1}^T
\end{aligned}
\end{equation*}

sendo que a matriz de transformação $[T]$ é ortogonal, ou seja:

\begin{equation*}
\underline{\underline{T}}_{1/0}^{-1} = \underline{\underline{T}}_{0/1}^T
\end{equation*}

Por analogia do desenvolvimento anterior obtém-se:

\begin{equation*}
\begin{aligned}
\underline{\underline{\sigma}}_0&=\underline{\underline{T}}_{1/0}\,\underline{\underline{\sigma}}_1~
\underline{\underline{T}}_{1/0}^T
\end{aligned}
\end{equation*}

**Determinação da matriz de tensão em $S_1$**

Os vetores de tensão que atuam nas facetas definidas pelos versores $\vec{n}_1,\vec{n}_2,\vec{n}_3$ têm componentes cartesianas em $S_0$:

\begin{equation*}
\begin{aligned}
\vec{t}{(\vec{n}_1)}_0 &= 5\sqrt{3}\vec{\imath}~+\sqrt{3}\vec{\jmath}~-~5/2\vec{k}\\
\vec{t}{(\vec{n}_2)}_0 &= 2\vec{\imath}~+5\vec{\jmath}\\
\vec{t}{(\vec{n}_3)}_0 &= -5\vec{\imath}~-\vec{\jmath}~-~(5\sqrt{3})/2\vec{k}\\
\end{aligned}
\end{equation*}

In [8]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

S0tn1 = np.array([[5*np.sqrt(3)],[np.sqrt(3)],[-5/2]])
S0tn2 = np.array([[2],[5],[0]])
S0tn3 = np.array([[-5],[-1],[-(5*np.sqrt(3))/2]])
print('Componentes dos vetores tensao no referencial S0 :')
print('tn1.S0 | tn2.S0 | tn3.S0')
for i in range(0,3):
    print(S0tn1[i],' ',S0tn2[i],' ',S0tn3[i])

Componentes dos vetores tensao no referencial S0 :
tn1.S0 | tn2.S0 | tn3.S0
[ 8.660]   [2]   [-5.000]
[ 1.732]   [5]   [-1.000]
[-2.500]   [0]   [-4.330]


Atendendo às expressões de mudança de
base, pode obter-se as componentes deste vetor de tensão no referencial $S_1$:

\begin{equation*}
\begin{aligned}
\underline{t}{(\vec{n}_1)}_1 &= \underline{\underline{T}}_{0/1}\cdot\!
\underline{t}{(\vec{n}_1)}_0 \\
\vec{t}{(\vec{n}_2)}_1 &= \underline{\underline{T}}_{0/1}\cdot\!\underline{t}{(\vec{n}_2)}_0 \\
\vec{t}{(\vec{n}_3)}_1 &= \underline{\underline{T}}_{0/1}\cdot\!
\vec{t}{(\vec{n}_3)}_0
\end{aligned}
\end{equation*}

In [9]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
S1tn1 = np.dot(Q01,S0tn1)
S1tn2 = np.dot(Q01,S0tn2)
S1tn3 = np.dot(Q01,S0tn3)

print('Componentes dos vetores tensao no referencial S1 :')
print('tn1.S1 | tn2.S1 | tn3.S1')
for i in range(0,3):
    print(S1tn1[i],' ',S1tn2[i],' ',S1tn2[i])

Componentes dos vetores tensao no referencial S1 :
tn1.S1 | tn2.S1 | tn3.S1
[ 6.250]   [ 1.732]   [ 1.732]
[ 1.732]   [ 5.000]   [ 5.000]
[-6.495]   [-1.000]   [-1.000]


A matriz do tensor das tensões no referencial $S_1(0,\vec{n}_1,\vec{n}_2,\vec{n}_3)$ será portanto dado por:

\begin{equation*}
\underline{t}_1 = \,\underline{\underline{\sigma}}_1\,\underline{n}_1
\end{equation*}

onde,

\begin{equation*}
\underline{\underline{\sigma}}_1 =
\begin{bmatrix}
\underline{t}{(\vec{n}_1)}_1 & \underline{t}{(\vec{n}_2)}_1 &
\underline{t}{(\vec{n}_3)}_1
\end{bmatrix}
\end{equation*}

ou seja, cada coluna da matriz de tensão $\tilde{\sigma}_1$ é formada pelas componentes das tensões $\,\vec{t}{(\vec{n}_1)}_1, \,\vec{t}{(\vec{n}_2)}_1, \,\vec{t}{(\vec{n}_3)}_1$ no referencial $S_1$, que atuam em facetas que contêm o ponto $P$ e cuja orientação é caraterizada pelos versoes $\vec{n}_1, \vec{n}_2, \vec{n}_3$.

In [10]:
sigma1 = np.hstack((S1tn1,S1tn2,S1tn3))
print('sigma1 = \n', sigma1)

sigma1 = 
 [[ 6.250  1.732 -6.495]
 [ 1.732  5.000 -1.000]
 [-6.495 -1.000 -1.250]]


Pelo que as componentes de $^0\underline{\underline{\sigma}}$, expressas no referencial $S_0$, são obtidas por:

\begin{equation*}
\begin{aligned}
&\underline{\underline{\sigma}}_0 = \underline{\underline{T}}_{1/0}\,\underline{\underline{\sigma}}_1~
\underline{\underline{T}}_{1/0}^T = \underline{\underline{T}}_{0/1}^T\,\underline{\underline{\sigma}}_1~
\underline{\underline{T}}_{0/1}
\end{aligned}
\end{equation*}

In [11]:
Q10 = np.transpose(Q01)
print('\n0[\sigma] = [T]1/0 1[\sigma] [T]1/0^T : --------------------------')
sigma0a = np.dot(Q10, np.dot(sigma1, np.transpose(Q10)))
print('\nsigma0 = \n', sigma0a)
print('\n0[\sigma] = [T]0/1^T 1[\sigma] [T]0/1 : ==========================')
sigma0b = np.dot( np.transpose(Q01), np.dot(sigma1,Q01))
print('\nsigma0 = \n', sigma0b)


0[\sigma] = [T]1/0 1[\sigma] [T]1/0^T : --------------------------

sigma0 = 
 [[ 10.000  2.000  0.000]
 [ 2.000  5.000  0.000]
 [ 0.000  0.000 -5.000]]

0[\sigma] = [T]0/1^T 1[\sigma] [T]0/1 : ==========================

sigma0 = 
 [[ 10.000  2.000  0.000]
 [ 2.000  5.000  0.000]
 [ 0.000  0.000 -5.000]]


#### c) Calcule as componentes normal e tangencial do vector tensão associado ao plano cuja normal faz ângulos iguais com ($\vec{\imath}, \vec{\jmath},\vec{k}$).<a name="C"></a>
([enunciatum](#PI22))

Normal a um plano que faz ângulos iguais com $\vec{\imath},\vec{\jmath},\vec{k}$. Partindo do produto interno entre versores de um sistema ortonormado têm-se:

\begin{equation*}
\begin{aligned}
&\vec{n}\cdot\vec{n} = n_i \cdot n_i = 1 ~\Leftrightarrow\\
&\underline{n}^T\cdot\underline{n} = \{n\}^T\cdot\{n\} =
\begin{bmatrix}
n_1 & n_2 & n_3
\end{bmatrix}
\begin{bmatrix}
n_1 \\ n_2 \\ n_3
\end{bmatrix} = n_1^2 + n_2^2 + n_3^2 = 1
\end{aligned}
\end{equation*}

Numa faceta igualmente inclinada sobre os eixos coordenados $(x_1,x_2,x_3)$, as componentes do versor normal são todas iguais: $n_1 = n_2 = n_3 = n$. Pelo que,

\begin{equation*}
n = \pm \frac{1}{\sqrt{3}}
\end{equation*}

Admitindo,

\begin{equation*}
\vec{n} = \frac{1}{\sqrt{3}}
\begin{bmatrix}
1 \\ 1\\ 1
\end{bmatrix}
\end{equation*}

O vetor tensão para esta orientação de faceta é obtido pela fórmula de Cauchy:

\begin{equation*}
\begin{aligned}
\vec{t}^{(\vec{n})} &= \tilde{\sigma}^T \cdot \vec{n}  \quad~\textrm{(notação direta)} \\
 t_i &= \sigma_{ji} \cdot n_j \quad\textrm{(notação indicial)}
\end{aligned}
\end{equation*}

A forma matricial da fórmula de Cauchy (para efeitos de cálculo) pode ser dada por:

\begin{equation*}
\begin{bmatrix}
t_1 \\ t_2 \\ t_3
\end{bmatrix} =
\begin{bmatrix}
\sigma_{11} & \sigma_{21} & \sigma_{31} \\
\sigma_{12} & \sigma_{22} & \sigma_{32} \\
\sigma_{13} & \sigma_{23} & \sigma_{33}
\end{bmatrix}
\begin{bmatrix}
n_1 \\ n_2 \\ n_3
\end{bmatrix}
\end{equation*}

Este vetor pode ainda ser decomposto pela soma de dois vetores ortogonais projetados em eixos normal ($\vec{n}$) e tangencial ($\vec{s}$) à faceta no ponto:

\begin{equation*}
\vec{t}^{(\vec{n})} = \sigma_n ~\vec{n} + \tau ~\vec{s}
\end{equation*}

A componente de tensão normal pode obter-se pelo produto escalar entre os vetores:

\begin{equation*}
\begin{aligned}
\sigma_n &= \vec{t}^{(\vec{n})} \cdot \vec{n} = t_i \cdot n_i = n_i \cdot \sigma_{ji} \cdot n_j \\
& = \begin{bmatrix}
n_1 & n_2 & n_3
\end{bmatrix}
\begin{bmatrix}
\sigma_{11} & \sigma_{21} & \sigma_{31} \\
\sigma_{12} & \sigma_{22} & \sigma_{32} \\
\sigma_{13} & \sigma_{23} & \sigma_{33}
\end{bmatrix}
\begin{bmatrix}
n_1 \\ n_2 \\ n_3
\end{bmatrix}
\end{aligned}
\end{equation*}

A componente de tensão de corte vem:

\begin{equation*}
\tau = \sqrt{||\vec{t}||^2 -\sigma_n^2}
= \sqrt{\vec{t}^{(\vec{n})} \cdot \vec{t}^{(\vec{n})} -\sigma_n^2}
\end{equation*}


In [12]:
vecm = np.array([1,1,1])
print('Vetor  = ',vecm)
verm = vecm/np.sqrt(np.dot(vecm,vecm))
print('Versor = ',verm)
vectens = np.dot(sigma0a,verm)
print('\nVetor tensão = ',vectens,' MPa')
tnormal = np.dot(vectens,verm)
print('\nComponente normal do vetor tnsão = ','{: 0.3f}'.format(tnormal),' MPa')
ttang = np.sqrt(np.dot(vectens,vectens)-tnormal**2)
print('Componente tangencial do vetor tnsão = ','{: 0.3f}'.format(ttang),' MPa')

Vetor  =  [1 1 1]
Versor =  [ 0.577  0.577  0.577]

Vetor tensão =  [ 6.928  4.041 -2.887]  MPa

Componente normal do vetor tnsão =   4.667  MPa
Componente tangencial do vetor tnsão =   7.134  MPa


#### Apêndice A

A escolha de vetores de base para um sistema de coordenadas $\vec{e}_i$ não é única. Contudo, é possível mostrar que as componentes de vetores e tensores expressos em diferentes sistemas de coordenadas podem ser relacionadas entre si através de leis de transformação adequadas.

Considere-se dois sistemas de coordenadas $\vec{e}_\alpha$ e $\vec{e}_i'$. Adopta-se a notação de _Sokolnikoff_ em que os índices Gregos ($\alpha$) referem a base original e os índices Romanos ($i$) referem a nova base. Deseja-se estabelecer as relações entre as componentes $\vec{e}_\alpha$ e $\vec{e}_i'$. Para esse efeito, é possível escrever os vetores da nova base $\vec{e}_i'$ como uma combinação linear dos vetores da base de partida $\vec{e}_\alpha$:

\begin{equation*}
\vec{e}_i' = Q_{\alpha i}~\vec{e}_\alpha \quad (i,\alpha = 1,2,3)
\end{equation*}

expandindo a expressão para o índice $\alpha$ resulta,

\begin{equation*}
\vec{e}_i' = Q_{1i}~\vec{e}_1 + Q_{2i}~\vec{e}_2 + Q_{3i}~\vec{e}_3
\end{equation*}

e, por exemplo, para $\vec{e}_1'$ vem:

\begin{equation*}
\begin{aligned}
\vec{e}_1' =
\begin{bmatrix}
Q_{11} & Q_{21} &  Q_{31}
\end{bmatrix}
\begin{bmatrix}
\vec{e}_1 \\ \vec{e}_2 \\ \vec{e}_3
\end{bmatrix} =
\begin{bmatrix}
\vec{e}_1\cdot \vec{e}_1' & \vec{e}_2\cdot \vec{e}_1' & \vec{e}_3\cdot \vec{e}_1'
\end{bmatrix}
\begin{bmatrix}
\vec{e}_1 \\ \vec{e}_2 \\ \vec{e}_3
\end{bmatrix}
\end{aligned}
\end{equation*}

em que $Q_{\alpha1}$ são os cossenos diretores: $\vec{e}_\alpha\cdot \vec{e}_i' = \cos(\vec{e}_i',\vec{e}_\alpha)$

Genarizando,

\begin{equation*}
\begin{bmatrix}
\vec{e}_1' \\ \vec{e}_2'\\ \vec{e}_3'
\end{bmatrix} =
\begin{bmatrix}
Q_{11} & Q_{21} &  Q_{31} \\
Q_{12} & Q_{22} &  Q_{32} \\
Q_{13} & Q_{23} &  Q_{33}
\end{bmatrix}
\begin{bmatrix}
\vec{e}_1 \\ \vec{e}_2 \\ \vec{e}_3
\end{bmatrix} =
\begin{bmatrix}
Q_{11} & Q_{12} &  Q_{13} \\
Q_{21} & Q_{22} &  Q_{23} \\
Q_{31} & Q_{32} &  Q_{33}
\end{bmatrix}^\top
\begin{bmatrix}
\vec{e}_1 \\ \vec{e}_2 \\ \vec{e}_3
\end{bmatrix}
\end{equation*}

ou,

\begin{equation*}
\begin{aligned}
\begin{bmatrix}
\vec{e}_1' \\ \vec{e}_2'\\ \vec{e}_3'
\end{bmatrix} =
\begin{bmatrix}
\vec{e}_1\cdot \vec{e}_1' & \vec{e}_2\cdot \vec{e}_1' &
\vec{e}_3\cdot \vec{e}_1' \\
\vec{e}_1\cdot \vec{e}_2' & \vec{e}_2\cdot \vec{e}_2' &
\vec{e}_3\cdot \vec{e}_2' \\
\vec{e}_1\cdot \vec{e}_3' & \vec{e}_2\cdot \vec{e}_3' & \vec{e}_3\cdot \vec{e}_3'
\end{bmatrix}
\begin{bmatrix}
\vec{e}_1 \\ \vec{e}_2 \\ \vec{e}_3
\end{bmatrix}
\end{aligned}
\end{equation*}

Considere-se o exemplo de uma mudança de coordenadas por rotação em torno do eixo comum $\vec{e}_3 \equiv \vec{e}_3'$, de um ângulo $\theta \in [0º,90º]$. Os vetores da nova base serão expressos pela seguinte combinação linear em relação aos vetores da base de origem:

\begin{equation*}
\begin{cases}
\vec{e}_1' = \cos\theta \vec{e}_1 + \cos(90-\theta)\vec{e}_2 \\
\vec{e}_2' = \cos(90+\theta)\vec{e}_1 + \cos\theta \vec{e}_2 \\
\vec{e}_3' = \vec{e}_3 \\
\end{cases}
\end{equation*}

A matriz de tranformação vem neste caso dada por:

\begin{equation*}
[Q]=
\begin{bmatrix}
\cos\theta & \sin\theta & 0 \\
-\sin\theta & \cos\theta & 0 \\
0 & 0 & 1
\end{bmatrix}
\end{equation*}

**Referências bibliográficas**

[1] E.B. Tadmor, R.E. Miller, R.S. Elliott - Continuum Mechanics and Thermodynamics: From Fundamental Concepts to Governing Equations, Cambridge University Press, 2012.

[2] S. Bechtel, R. Lowe. Fundamentals of Continuum Mechanics With Applications to Mechanical, Thermomechanical, and Smart Materials. Academic Press, 2014.

---

Copyright (c) [Mecânica dos Sólidos I - DEMI - NOVA-SST]

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>
