<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/iLogos/nsst.jpg" width="400" height="100">

# DEMI | NOVA SST

## Mecânica dos Sólidos I

# I.2 Transformação de tensões. Tensões principais. Direções principais.

## Problema 7 <a name="PI27"></a>

Considere dois sistemas de coordenadas $S_0(O,\vec{\imath},\vec{\jmath}, \vec{k})$ e $S_1(O,\vec{\imath}',\vec{\jmath}',\vec{k}')$, com a mesma origem mas orientações diferentes. A matriz de transformação entre $S_0$ e $S_1$, e a matriz de tensão em $S_0$ são dadas por:

\begin{equation*}
\begin{array}{c|ccc}
& x & y & z \\ \hline
x' & 2/7 & 3/7 & 6/7 \\
y' & 3/7 & -6/7 & 2/7 \\
z' & 6/7 & 2/7 & -3/7 \\\hline
\end{array} \quad \quad \quad
\sigma_{ij/0} =
\begin{bmatrix}
14 & 0 & 21 \\
0  & 21 & 0 \\
21 & 0 & 7
\end{bmatrix}
\end{equation*}

a) Calcule os vectores tensão nos planos perpendiculares aos eixos $x’,y’,z’$.

b) Obtenha as suas componentes no referencial $x’,y’,z’$ para obter as componentes de $\sigma_{ij}$.


## Resolução

#### a) Calcule os vectores tensão nos planos perpendiculares aos eixos $x’,y’,z’$.

As colunas da matriz do tensor das tensões representam as componentes cartesianas dos vetores de tensão que atuam nas facetas perpendiculares aos eixos coordenados $(x,y,z,)$:

\begin{equation*}
\begin{aligned}
\vec{t}(\vec{\imath}) &= \sigma_{xx} \vec{\imath} + \sigma_{xy} \vec{\jmath} + \sigma_{xz} \vec{k} =
14 \vec{\imath} + 21 \vec{k} \\
\vec{t}(\vec{\jmath})_0 &= \sigma_{yx} \vec{\imath} + \sigma_{yy} \vec{\jmath} + \sigma_{yz} \vec{k} =
21 \vec{\jmath}  \\
\vec{t}(\vec{k})_0 &= \sigma_{zx} \vec{\imath} + \sigma_{zy} \vec{\jmath} + \sigma_{zz} \vec{k} =
21 \vec{\imath} + 7 \vec{k} \\
\end{aligned}
\end{equation*}

Conhecida a matriz de tensão em facetas perpendiculares aos eixos coordenadados $(x,y,z)$ de um sistema de coordenadas ortonormado e direto, a fórmula de Cauchy permite determinar o vetor tensão em qualquer faceta cuja normal exterior é $\vec{n}$:

\begin{equation*}
\vec{t}(p,\vec{n}) = \tilde{\sigma}^T(p) \cdot \vec{n}
\end{equation*}

Os vetores de tensão que atuam em facetas perpendiculares aos eixos coordenados $(x’,y’,z’)$ podem obter-se por:

\begin{equation*}
\begin{aligned}
\vec{t}^{\,(\vec{\imath}~')}_{0} & =~\tilde{\sigma}^T_{0}\cdot~\vec{\imath}~'_{0}\\
\vec{t}^{(\vec{\jmath}~')}_0 &=~\tilde{\sigma}^T_0\cdot~\vec{\jmath}~'_{0}  \\
\vec{t}^{(\vec{k}~')}_0 &=~\tilde{\sigma}^T_0\cdot~\vec{k}~'_{0}
\end{aligned}
\end{equation*}


In [4]:
import numpy as np

def T01(l1,m1,n1,l2,m2,n2,l3,m3,n3):
    return np.array([[l1,m1,n1],[l2,m2,n2],[l3,m3,n3]])

def MatTTens(S11,S12,S13,S22,S23,S33):
    return np.array([[S11,S12,S13],[S12,S22,S23],[S13,S23,S33]])

def vetorTens(t1,t2,t3):
    return np.array([t1,t2,t3])

def versor(l,m,n):
    return np.array([l,m,n])

tt0 = MatTTens(14,0,21,21,0,7) # unidades; MPa
print('tt0 = \n',tt0)

x1 = versor(2/7,3/7,6/7)
ti1 = np.dot(tt0,x1)
print('ti1 (S0) = ',ti1)

y1 = versor(3/7,-6/7,2/7)
tj1 = np.dot(tt0,y1)
print('tj1 (S0) = ',tj1)

z1 = versor(6/7,2/7,-3/7)
tk1 = np.dot(tt0,z1)
print('tk1 (S0) = ',tk1)

tt0 = 
 [[14  0 21]
 [ 0 21  0]
 [21  0  7]]
ti1 (S0) =  [ 22.000  9.000  12.000]
tj1 (S0) =  [ 12.000 -18.000  11.000]
tk1 (S0) =  [ 3.000  6.000  15.000]


#### b) Obtenha as suas componentes no referencial $x’,y’,z’$ para obter as componentes de $\sigma_{ij}$.

Considere-se dois sistemas de coordenadas distintos, $S_0(0,x,y,z)$ e $S_1(0,x',y',z')$. Os cosenos diretores dos ângulos entre os eixos coordenados $(x,y,z)$ e os eixos coordenados $(x',y',z')$ são dados pela seguinte tabela:

\begin{equation*}
\begin{array}{c|ccc}
\hline  & x & y & z \\\hline
  x' & l_1 & m_1 & n_1 \\
  y' & l_2 & m_2 & n_2 \\
  z' & l_3 & m_3 & n_3 \\\hline
\end{array}
\end{equation*}

Cada linha da matriz $(l,m,n)$ traduz o produto escalar entre os eixos coordenados $(x',y',z')$ no sistema de coordenadas $S_0(0,x,y,z)$. Para a primeira direção $x'$, têm-se portanto: $l_1=\cos(x',x), m_1=\cos(x',y), n_1=\cos(x',z)$. Por outro lado, cada coluna traduz o produto escalar entre os eixos coordenados $(x,y,z)$ no sistema de coordenadas $S_1(0,x',y',z')$. A título de exempmlo, para a direção $x$, têm-se: $l_1=\cos(x,x'), l_2=\cos(x,y'), l_3=\cos(x,z')$.

A matriz de tansformação do sistema $S_0$ para um novo referencial $S_1$ vem assim dada:

\begin{equation*}
[T_{01}] =
\begin{bmatrix}
l_1 & m_1 & n_1 \\
l_2 & m_2 & n_2 \\
l_3 & m_3 & n_3
\end{bmatrix} =
\begin{bmatrix}
\cos(x',x) & \cos(x',y) & \cos(x',z) \\
\cos(y',x) & \cos(y',y) & \cos(y',z) \\
\cos(z',x) & \cos(z',y) & \cos(z',z)
\end{bmatrix}
\end{equation*}

De acordo com a lei de transformação de um tensor de segunda ordem simétrico vem:

\begin{equation*}
[\sigma_1] = [T_{01}][\sigma_0][T_{01}]^T
\end{equation*}

In [5]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

T = T01(2/7,3/7,6/7,3/7,-6/7,2/7,6/7,2/7,-3/7)
print('T = \n',T)

tt1 = np.dot(T,np.dot(tt0,np.transpose(T)))
print('tt1 = \n',tt1)

T = 
 [[ 0.286  0.429  0.857]
 [ 0.429 -0.857  0.286]
 [ 0.857  0.286 -0.429]]
tt1 = 
 [[ 20.429  5.143  16.286]
 [ 5.143  23.714  0.429]
 [ 16.286  0.429 -2.143]]


De forma equivalente, as componentes dos vetores de tensão que atuam em facetas perpendiculares aos eixos coordenados $(x’,y’,z’)$ expressos no sistema de coordenadas $S_1(x',y',z')$ podem obter-se pelas seguintes transformações lineares:

\begin{equation*}
\begin{aligned}
\vec{t}^{~(\vec{\imath}~')}_1 &= [T_{01}]~\vec{t}^{~(\vec{\imath})}_0 \\
\vec{t}^{~(\vec{\jmath}~')}_1 &= [T_{01}]~\vec{t}^{~(\vec{\jmath})}_0 \\
\vec{t}^{~(\vec{k}~')}_1 &= [T_{01}]~\vec{t}^{~(\vec{k})}_0
\end{aligned}
\end{equation*}

In [6]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

ti1S1 = np.dot(T,ti1)
print('\nti1 = ',ti1S1)
tj1S1 = np.dot(T,tj1)
print('tj1 = ',tj1S1)
tk1S1 = np.dot(T,tk1)
print('tk1 = ',tk1S1)


ti1 =  [ 20.429  5.143  16.286]
tj1 =  [ 5.143  23.714  0.429]
tk1 =  [ 16.286  0.429 -2.143]


---

Copyright (c) [Mecânica dos Sólidos I - DEMI - NOVA-SST]

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>
