<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/iLogos/nsst.jpg" width="400" height="100">

# DEMI | NOVA SST

## Mecânica dos Sólidos I

# II. Análise de extensões. Extensometria. Equações da compatibilidade.

## Problema 9 <a name="PII59"></a>

Considere o seguinte campo de deslocamentos de um sólido deformável:

\begin{equation*}
\vec{u} = (x^2 + y) \vec\imath + (3 + z) \vec\jmath + (x^2 + 2y) \vec{k}
\end{equation*}

Determine as deformações principais no ponto $(3,1,-2)$ e a direção da deformação principal mínima.

## Resolução

Componentes do tensor das deformações infinitésimais:

\begin{equation*}
\varepsilon_{ij} = \frac{1}{2}\left( \frac{\partial u_i}{\partial x_j}
+ \frac{\partial u_j}{\partial x_i} \right)
\end{equation*}

Explicitamente:

\begin{equation*}
\begin{aligned}
\varepsilon_{xx} &= \frac{\partial u}{\partial x} \\
\varepsilon_{yy} &= \frac{\partial v}{\partial y} \\
\varepsilon_{zz} &= \frac{\partial w}{\partial z} \\
\varepsilon_{xy} &= \frac{1}{2}\left( \frac{\partial u}{\partial y} + \frac{\partial v}{\partial x} \right)  = \frac{1}{2}\gamma_{xy}\\
\varepsilon_{yz} &= \frac{1}{2}\left( \frac{\partial v}{\partial z} + \frac{\partial w}{\partial y} \right)  = \frac{1}{2} \gamma_{yz}\\
\varepsilon_{xz} &= \frac{1}{2}\left( \frac{\partial u}{\partial z} + \frac{\partial w}{\partial x} \right) = \frac{1}{2} \gamma_{xz}\\
\end{aligned}
\end{equation*}

Na forma matricial,

A matriz das deformações vem dada por:

\begin{equation*}
\begin{aligned}
\underline{\underline{\varepsilon}} \equiv [\varepsilon] \equiv \varepsilon_{ij}
&=
\begin{bmatrix}
\varepsilon_{xx} & \varepsilon_{xy} & \varepsilon_{xz}\\
\varepsilon_{yx} & \varepsilon_{yy} & \varepsilon_{yz} \\
\varepsilon_{zx} & \varepsilon_{zy} & \varepsilon_{zz} \\
\end{bmatrix} =
\begin{bmatrix}
\varepsilon_{xx} & \gamma_{xy}/2 & \gamma_{xz}/2 \\
\gamma_{yx}/2 & \varepsilon_{yy} & \gamma_{yz}/2 \\
\gamma_{zx}/2 & \gamma_{yz}/2 & \varepsilon_{zz} \\
\end{bmatrix} \\
&=
\begin{bmatrix}
\displaystyle\frac{\partial u}{\partial x}
& \displaystyle\frac{1}{2}\left(\frac{\partial u}{\partial y} + \frac{\partial v}{\partial x} \right)
& \displaystyle\frac{1}{2}\left(\frac{\partial u}{\partial z} + \frac{\partial w}{\partial x} \right) \\
\displaystyle\frac{1}{2}\left(\frac{\partial v}{\partial x} + \frac{\partial u}{\partial y} \right)
& \displaystyle\frac{\partial v}{\partial y}
& \displaystyle\frac{1}{2}\left(\frac{\partial v}{\partial z} + \frac{\partial w}{\partial y} \right) \\
\displaystyle\frac{1}{2}\left(\frac{\partial w}{\partial x} + \frac{\partial u}{\partial z} \right)
& \displaystyle\frac{1}{2}\left(\frac{\partial v}{\partial z} + \frac{\partial w}{\partial y} \right)
& \displaystyle\frac{\partial w}{\partial z} \\
\end{bmatrix}
\end{aligned}
\end{equation*}

In [1]:
import numpy as np
import sympy as sy
from sympy import diff, Derivative
from sympy.solvers import solve
from sympy import symbols, sympify, factor, collect
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
from pylab import meshgrid,cm,imshow,contour,clabel,colorbar,axis,title,show

u, v, w, x, y, z = symbols('u v w x y z')

def u(x,y): return x**2 + y
def v(z): return 3 + z
def w(x,y): return x**2 + 2*y

u1 = u(x,y)
v1 = v(z)
w1 = w(x,y)

print('matriz das deformações [D]:\n')

exx = diff(u1, x)
print('exx = du/dx :',exx)
eyy = diff(v1, y)
print('eyy = dv/dy :',eyy)
ezz = diff(w1, z)
print('ezz = dw/dz :',ezz)
exy  = 0.5*(diff(u1, y) + diff(v1, x) )
print('exy = 1/2 gxy = 1/2 (du/dy + dv/dx )  :',exy)
exz  = 0.5*(diff(u1, z) + diff(w1, x) )
print('exz = 1/2 gxz = 1/2 (du/dz + dw/dx )  :',exz)
eyz  = 0.5*(diff(v1, z) + diff(w1, y) )
print('eyz = 1/2 gxy = 1/2 (dv/dz + dw/dy )  :',eyz)

def mD(exx,exy,exz,eyy,eyz,ezz):
    return np.array([[exx,exy,exz],[exy,eyy,eyz],[exz,eyz,ezz]])

mD0 = mD(exx,exy,exz,eyy,eyz,ezz)
print('\n[mD0] = \n',mD0)

# ponto
Px0, Py0, Pz0 = 3, 1, -2

exx = float(exx.subs({x:Px0,y:Py0,z:Pz0}))
eyy = float(eyy.subs({x:Px0,y:Py0,z:Pz0}))
ezz = float(ezz.subs({x:Px0,y:Py0,z:Pz0}))
exy = float(exy.subs({x:Px0,y:Py0,z:Pz0}))
exz = float(exz.subs({x:Px0,y:Py0,z:Pz0}))
eyz = float(eyz.subs({x:Px0,y:Py0,z:Pz0}))

mDP = mD(exx,exy,exz,eyy,eyz,ezz)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
print('\n[D(P)] = \n',mDP)

matriz das deformações [D]:

exx = du/dx : 2*x
eyy = dv/dy : 0
ezz = dw/dz : 0
exy = 1/2 gxy = 1/2 (du/dy + dv/dx )  : 0.500000000000000
exz = 1/2 gxz = 1/2 (du/dz + dw/dx )  : 1.0*x
eyz = 1/2 gxy = 1/2 (dv/dz + dw/dy )  : 1.50000000000000

[mD0] = 
 [[2*x 0.500000000000000 1.0*x]
 [0.500000000000000 0 1.50000000000000]
 [1.0*x 1.50000000000000 0]]

[D(P)] = 
 [[ 6.000  0.500  3.000]
 [ 0.500  0.000  1.500]
 [ 3.000  1.500  0.000]]


Para um dado tensor de deformações definido num ponto $P$ de um objeto, torna-se relevante saber determinar os valores extremos das extensões lineares e das distorções de corte, máximos e mínimas. Este problema é equivalente à determinação dos valores e vetores próprios de uma matriz.

As deformações principais e as direções principais resultam da análise do seguinte sistema de equações:

\begin{equation*}
\begin{aligned}
(\varepsilon_{xx} - \epsilon) n_x + \varepsilon_{xy} n_y + \varepsilon_{xz} n_z = 0 \\
\varepsilon_{yx} n_x + (\varepsilon_{yy} - \epsilon) n_y + \varepsilon_{yz} n_z = 0 \\
\varepsilon_{zx} n_x + \varepsilon_{zy} n_y + (\varepsilon_{zz} - \epsilon) n_z= 0 \\
\end{aligned}
\end{equation*}

Este sitema de equações é homogéneo em $n_x, n_y, n_z$. A existência de uma solução não-trivial impica que seja nulo o seguinte determinante:

\begin{equation*}
\begin{vmatrix}
(\varepsilon_{xx} - \epsilon) & \varepsilon_{xy} & \varepsilon_{xz} \\
\varepsilon_{yx} & (\varepsilon_{yy} - \epsilon) &  \varepsilon_{yz} \\
\varepsilon_{zx} & \varepsilon_{zy} & (\varepsilon_{zz} - \epsilon) \\
\end{vmatrix} = 0
\end{equation*}

O desenvolvimento algébrico deste determinante conduz ao chamado polonímio ou equação caraterística:

\begin{equation*}
p(\epsilon) = \epsilon^3 - \mathrm{I_\epsilon}\epsilon^2 + \mathrm{II_\epsilon}\epsilon - \mathrm{III_\epsilon}
\equiv
\epsilon^3 - J_1 \epsilon^2 + J_2\epsilon - J_3  = 0
\end{equation*}

onde,

\begin{equation*}
\begin{aligned}
J_1 & = \mathrm{Tr}(\varepsilon_{ij}) = \varepsilon_{xx} + \varepsilon_{yy} + \varepsilon_{zz}\\
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
J_2 & = \frac{1}{2}\left[ \mathrm{Tr}(\varepsilon_{ij})^2 - \mathrm{Tr}(\varepsilon_{ij}^2) \right] =
\frac{1}{2}\left( \varepsilon_{ii}\varepsilon_{jj} - \varepsilon_{ij}\varepsilon_{ji} \right) \\
& =
\begin{vmatrix}
\varepsilon_{xx} & \varepsilon_{xy} \\
\varepsilon_{yx} & \varepsilon_{yy} \\
\end{vmatrix} +
\begin{vmatrix}
\varepsilon_{yy} & \varepsilon_{yz} \\
\varepsilon_{zy} & \varepsilon_{zz} \\
\end{vmatrix} +
\begin{vmatrix}
\varepsilon_{xx} & \varepsilon_{xz} \\
\varepsilon_{zx} & \varepsilon_{zz} \\
\end{vmatrix}%
\end{aligned}
\end{equation*}

\begin{equation*}
\begin{aligned}
J_3 & = \mathrm{det}(\varepsilon_{ij}) = \begin{vmatrix}
\varepsilon_{xx} & \varepsilon_{xy} & \varepsilon_{xz}\\
\varepsilon_{yx} & \varepsilon_{yy} & \varepsilon_{yz}\\
\varepsilon_{zx} & \varepsilon_{zy} & \varepsilon_{zz}\\
\end{vmatrix}\\
\end{aligned}
\end{equation*}

De observar que os invariantes $J_2$ e $J_3$ são em função das componentes tensoriais de corte, $\varepsilon_{yz}, \varepsilon_{xz}, \varepsilon_{yx}$ e não as componentes de corte de engenharia $\gamma_{yz}, \gamma_{xz}, \gamma_{yx}$.

Para um dado estado de deformação no ponto $P$, se a deformação ou extensão linear $\epsilon$ é um valor extremo numa direção $\vec{n}$, então esta é uma deformação principal no ponto $P$ e $\vec{n}$ é uma direção principal de deformação associada a $\epsilon$.

Para cada estado de deformação existem pelos menos três eixos principais, mutuamente perpendiculares entre si e no máximo três deformações principais distintas. As deformações principais, $\epsilon_\mathrm {I}$, $\epsilon_\mathrm{II}$, $\epsilon_\mathrm{III}$ são as raizes do seguinte polinómio ou equação caraterística (de oderm três ou cúbica):

\begin{equation*}
\epsilon^3 - J_\mathrm{I}\epsilon^2 + J_\mathrm{II}\epsilon - J_\mathrm{III} = 0
\end{equation*}

em que $J_\mathrm{I}$, $J_\mathrm{II}$ e $J_\mathrm{III}$ são o primeiro, segundo e terceiro invariantes do tensor das deformações.

In [2]:
print('\n Calculo dos invariantes pela matriz das deformações: ............................')
print(' - valores próprios = deformações principais -')

J1 = np.trace(mDP)
print('1º Invariante, J1:', '{:.5e}'.format(J1))

J2 = 0.5*(np.trace(mDP)**2 -np.trace(np.dot(mDP,mDP)))
print('2º Invariante, I2 :', '{:.5e}'.format(J2))

J3 = np.linalg.det(mDP)
print('3º Invariante, I3 :', '{:.5e}'.format(J3))

print('\n Resolucao Numerica - Numpy : ............................')
valpropriosN = np.roots([1,-J1,J2,-J3])
valpropriosN = -np.sort(-valpropriosN)
print('Roots = ',valpropriosN)

eI = valpropriosN[0]
print('\nExtensão principal eI : ','{:.3f}'.format(eI),' def')
eII = valpropriosN[1]
print('Extensão principal eII : ','{:.3f}'.format(eII),' def')
eIII = valpropriosN[2]
print('Extensão principal eIII : ','{:.3f}'.format(eIII),' def')



 Calculo dos invariantes pela matriz das deformações: ............................
 - valores próprios = deformações principais -
1º Invariante, J1: 6.00000e+00
2º Invariante, I2 : -1.15000e+01
3º Invariante, I3 : -9.00000e+00

 Resolucao Numerica - Numpy : ............................
Roots =  [ 7.391  0.609 -2.000]

Extensão principal eI :  7.391  def
Extensão principal eII :  0.609  def
Extensão principal eIII :  -2.000  def


As direções principais associadas a $\epsilon_\mathrm{I}$, $\epsilon_\mathrm{II}$ e $\epsilon_\mathrm{III}$ são obtidas substituindo $\epsilon_i~(i = 1, 2, 3)$ nas seguintes equações, resolvendo-as para $n_x$, $n_y$ e $n_z$:

\begin{equation*}
\begin{aligned}
(\varepsilon_{xx}-\epsilon_i) n_x + \varepsilon_{xy} n_y + \varepsilon_{xz} n_z &= 0 \\
\varepsilon_{xy} n_x + (\varepsilon_{yy}-\epsilon_i) n_y + \varepsilon_{yz} n_z &= 0 \\
\varepsilon_{xy} n_x + \varepsilon_{yz} n_y + (\varepsilon_{zz}-\epsilon_i) n_z &= 0 \\
n_x^2 + n_y^2 + n_z^2 &= 0
\end{aligned}
\end{equation*}

Se as três extensões principais forem distintas, $\epsilon_\mathrm{I} > \epsilon_\mathrm{II} > \epsilon_\mathrm{III}$, então os eixos $\vec{n}_\mathrm{I}, \vec{n}_\mathrm{II}, \vec{n}_\mathrm{III}$ são únicas e mutuamente perpendiculares.

Se, $\epsilon_\mathrm{I} = \epsilon_\mathrm{II} \ne \epsilon_\mathrm{III}$, então o eixo $\vec{n}_\mathrm{III}$ é único e todas as direções perpendicular a $\vec{n}_\mathrm{III}$ são uma direção principal associada a $\epsilon_\mathrm{I} = \epsilon_\mathrm{II}$. Se $\epsilon_\mathrm{I} = \epsilon_\mathrm{II} = \epsilon_\mathrm{III}$, então toda as direções são uma direção principal de deformação.

In [3]:
nx,ny,nz = symbols('nx ny nz')

def eq1(md,nx,ny,nz,vp): return (md[0,0] - vp)*nx + md[0,1]*ny + md[0,2]*nz
def eq2(md,nx,ny,nz,vp): return md[1,0]*nx + (md[1,1] - vp)*ny + md[1,2]*nz
def eq3(md,nx,ny,nz,vp): return md[2,0]*nx + md[2,1]*ny + (md[2,2] - vp)*nz
def eq4(nx,ny,nz): return nx**2 + ny**2 + nz**2 - 1

def versor(e1,e2,e3): return np.array([e1,e2,e3])

def VP1(mDP,eI,i):
    # 1 valor proprio -------------------
    print('\nVetor próprio associado a eI = ','{:.3f}'.format(eI),'.............................')
    print('\n(i) Sistema de equações:')
    E1 = eq1(mDP,nx,ny,nz,eI); print(E1,' = 0')
    E2 = eq2(mDP,nx,ny,nz,eI); print(E2,' = 0')
    E3 = eq3(mDP,nx,ny,nz,eI); print(E3,' = 0')
    E4 = eq4(nx,ny,nz); print(E4,' = 0')
    VetProp1 = solve([E1,E2,E4], [nx,ny,nz], dict=True)
    l1 = float(VetProp1[i][nx])
    m1 = float(VetProp1[i][ny])
    n1 = float(VetProp1[i][nz])
    print('\n (ii) vec{nI} = (','{:.3f}'.format(l1),') e1 + (','{:.3f}'.format(m1),') e2 + (','{:.3f}'.format(n1),') e3')
    return versor(l1,m1,n1)

def VP2(mDP,eII,i):
    # 2 valor proprio -------------------
    print('\nVetor próprio associado a eII = ','{:.3f}'.format(eII),' .............................')
    print('\n(i) Sistema de equações:')
    E1 = eq1(mDP,nx,ny,nz,eII); print(E1,' = 0')
    E2 = eq2(mDP,nx,ny,nz,eII); print(E2,' = 0')
    E3 = eq3(mDP,nx,ny,nz,eII); print(E3,' = 0')
    E4 = eq4(nx,ny,nz); print(E4,' = 0')
    VetProp2 = solve([E1,E3,E4], [nx,ny,nz], dict=True)
    l2 = float(VetProp2[i][nx])
    m2 = float(VetProp2[i][ny])
    n2 = float(VetProp2[i][nz])
    print('\n (ii) vec{nII} = (','{:.3f}'.format(l2),') e1 + (','{:.3f}'.format(m2),') e2 + (','{:.3f}'.format(n2),') e3')
    return versor(l2,m2,n2)

def  VP3(mDP,eIII,i):
    # 3 valor proprio -------------------
    print('\nVetor próprio associado a eIII = ','{:.3f}'.format(eIII),' .............................')
    print('\n(i) Sistema de equações:')
    E1 = eq1(mDP,nx,ny,nz,eIII); print(E1,' = 0')
    E2 = eq2(mDP,nx,ny,nz,eIII); print(E2,' = 0')
    E3 = eq3(mDP,nx,ny,nz,eIII); print(E3,' = 0')
    E4 = eq4(nx,ny,nz); print(E4,' = 0')
    VetProp3 = solve([E1,E2,E4], [nx,ny,nz], dict=True)
    l3 = float(VetProp3[i][nx])
    m3 = float(VetProp3[i][ny])
    n3 = float(VetProp3[i][nz])
    print('\n (iii) vec{nIII} = (','{:.3f}'.format(l3),') e1 + (','{:.3f}'.format(m3),') e2 + (','{:.3f}'.format(n3),') e3')
    return versor(l3,m3,n3)

nI = VP1(mDP,eI,1)
nII = VP2(mDP,eII,1)
nIII = VP3(mDP,eIII,1)

print('\n Versores principais: verificação')
print('dot(vpk,vpk) = ','{:.1f}'.format(np.dot(nI,nI)),'|', '{:.1f}'.format(np.dot(nII,nII)),'|','{:.1f}'.format(np.dot(nIII,nIII)))
print('dot(vpi,vpj) = ','{:.1f}'.format(np.abs(np.dot(nI,nII))),'|','{:.1f}'.format(np.abs(np.dot(nII,nIII))),'|','{:.0f}'.format(np.abs(np.dot(nI,nIII))))

np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
mT0P = np.concatenate((nI, nII, nIII))
mT0P = mT0P.reshape(3,3)
print('\n [T] = \n', mT0P)
print('\n det(T) = ','{:.2f}'.format(np.linalg.det(mT0P)))

print('\n  Ângulos : S0 - SP  ººººººººººººººººººººººººººººº')
print(' ang (   nI = x* ; x0,y0,z0 ) = ',np.rad2deg(np.arccos(nI)),' (Deg)')
print(' ang (  nII = y* ; x0,y0,z0 ) = ',np.rad2deg(np.arccos(nII)),' (Deg)')
print(' ang ( nIII = z* ; x0,y0,z0 ) = ',np.rad2deg(np.arccos(nIII)),' (Deg)')

print('\nverificacao: .............. ')
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
epsPs0 = np.dot(mT0P,np.dot(mDP,np.transpose(mT0P)))
print('Matriz deformação principal = \n',epsPs0,' def')


Vetor próprio associado a eI =  7.391 .............................

(i) Sistema de equações:
-1.39116499156264*nx + 0.5*ny + 3.0*nz  = 0
0.5*nx - 7.39116499156264*ny + 1.5*nz  = 0
3.0*nx + 1.5*ny - 7.39116499156264*nz  = 0
nx**2 + ny**2 + nz**2 - 1  = 0

 (ii) vec{nI} = ( 0.907 ) e1 + ( 0.142 ) e2 + ( 0.397 ) e3

Vetor próprio associado a eII =  0.609  .............................

(i) Sistema de equações:
5.39116499156263*nx + 0.5*ny + 3.0*nz  = 0
0.5*nx - 0.608835008437366*ny + 1.5*nz  = 0
3.0*nx + 1.5*ny - 0.608835008437366*nz  = 0
nx**2 + ny**2 + nz**2 - 1  = 0

 (ii) vec{nII} = ( 0.326 ) e1 + ( -0.833 ) e2 + ( -0.447 ) e3

Vetor próprio associado a eIII =  -2.000  .............................

(i) Sistema de equações:
8.0*nx + 0.5*ny + 3.0*nz  = 0
0.5*nx + 2.0*ny + 1.5*nz  = 0
3.0*nx + 1.5*ny + 2.0*nz  = 0
nx**2 + ny**2 + nz**2 - 1  = 0

 (iii) vec{nIII} = ( 0.267 ) e1 + ( 0.535 ) e2 + ( -0.802 ) e3

 Versores principais: verificação
dot(vpk,vpk) =  1.0 | 1.0 | 1.0
dot(vpi,vpj

---

Copyright (c) [Mecânica dos Sólidos I - DEMI - NOVA-SST]

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>