<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/iLogos/nsst.jpg" width="400" height="100">

# DEMI | NOVA SST

## Mecânica dos Sólidos I

# II. Análise de extensões. Extensometria. Equações da compatibilidade.

## Problema 8 <a name="PII58"></a>

Um componente de um equipamento industrial na forma de bloco paralelepipédico é deformado, adquirindo a forma definida pelos segmentos de reta a tracejado, como ilustrado na figura. Considerando pequenos deslocamentos, o componente está sujeito ao seguinte campo de deslocamentos:

\begin{equation*}
u=C_1XYZ~;\qquad v=C_2XYZ~;\qquad w=C_3XYZ.
\end{equation*}

[(a)](#A) Determine o estado de deformação no ponto E, sabendo que as coordenadas de E $^\star$ (E na configuração deformada) são (X;Y;Z) =(1,504; 1,002; 1,996) (m).

[(b)](#B) Determine a deformação normal no ponto E na direcção da linha EA.

[(c)](#C) Qual o valor da distorção angular no plano definido pelos versores das direções das linhas EA e EF?

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/Notebooks/Au05/Au05_P008_i1.jpg"
width="300" height="375">


## Resolução

#### a) Determine o estado de deformação no ponto E, sabendo que as coordenadas de E $^\star$ (E na configuração deformada) são (X;Y;Z) =(1,504; 1,002; 1,996) (m). <a name="A"></a>

([enunciatum](#PII58))

Por definição de vetor deslocamento, no ponto E têm-se:

\begin{equation*}
\vec{u} = \vec{r}_{E^\star}-\vec{R}_{E}
\end{equation*}

cujas componentes escalares no referencial dado são:

\begin{equation*}
\begin{aligned}
u_x \equiv u(X,Y,Z) &= x_{E^\star} - X_E = C_1XYZ\\
u_y \equiv v(X,Y,Z) &= y_{E^\star} - Y_E = C_2XYZ \\
u_z \equiv w(X,Y,Z) &= z_{E^\star} - Z_E = C_3XYZ
\end{aligned}
\end{equation*}

Os coeficientes $C_1$, $C_2$ e $C_3$ podem ser obtidos a partir das expressões cartesianas do campo de deslocamentos e pelo conhecimento do deslocamento do ponto E $^\star$.

In [2]:
import sympy as sy
from sympy.solvers import solve

# unit: m
XE, YE, ZE = 1.5, 1.0, 2.0

xE, yE, zE = 1.504, 1.002, 1.996

u = xE - XE
print(f'u = {u:.3f} m')
v = yE - YE
print(f'v = {v:.3f} m')
w = zE - ZE
print(f'w = {w:.3f} m')

c1, c2, c3, X, Y, Z = sy.symbols('c1 c2 c3 X Y Z')

def u1(c1,X,Y,Z): return c1*X*Y*Z
def u2(c2,X,Y,Z): return c2*X*Y*Z
def u3(c3,X,Y,Z): return c3*X*Y*Z

EQ1 = u - u1(c1,X,Y,Z)
EQ2 = v - u2(c2,X,Y,Z)
EQ3 = w - u3(c3,X,Y,Z)
sol = solve({EQ1,EQ2,EQ3},{c1,c2,c3})

print('XE*YE*ZE = ',XE*YE*ZE)
C1 = sol[c1]
NC1 = C1.subs({(X,XE),(Y,YE),(Z,ZE)})
print(f'C1 = {C1}  | N[C1] = {NC1:.5f}')

C2 = sol[c2]
NC2 = C2.subs({(X,XE),(Y,YE),(Z,ZE)})
print(f'C2 = {C2}  | N[C2] = {NC2:.5f}')

C3 = sol[c3]
NC3 = C3.subs({(X,XE),(Y,YE),(Z,ZE)})
print(f'C3 = {C3} | N[C3] = {NC3:.5f}')

u = 0.004 m
v = 0.002 m
w = -0.004 m
XE*YE*ZE =  3.0
C1 = 0.004/(X*Y*Z)  | N[C1] = 0.00133
C2 = 0.002/(X*Y*Z)  | N[C2] = 0.00067
C3 = -0.004/(X*Y*Z) | N[C3] = -0.00133


Pelo que

\begin{equation*}
\begin{aligned}
u(X,Y,Z) &= \frac{0.004}{3}XYZ\\
v(X,Y,Z) &= \frac{0.002}{3}XYZ\\
w(X,Y,Z) &= -\frac{0.004}{3}XYZ
\end{aligned}
\end{equation*}

**Deformação infinitesimal**

As componentes cartesianas do tensor das deformações infinitesimais
são dadas por:

\begin{equation*}
\varepsilon_{ij} = \frac{1}{2}\left( \frac{\partial u_i}{\partial x_j}
+ \frac{\partial u_j}{\partial x_i} \right)
\end{equation*}

Explicitamente:

\begin{equation*}
\begin{aligned}
\varepsilon_{xx} &= \frac{\partial u}{\partial x} \\
\varepsilon_{yy} &= \frac{\partial v}{\partial y} \\
\varepsilon_{zz} &= \frac{\partial w}{\partial z} \\
\varepsilon_{xy} &= \frac{1}{2}\left( \frac{\partial u}{\partial y} + \frac{\partial v}{\partial x} \right)  = \frac{1}{2}\gamma_{xy}\\
\varepsilon_{yz} &= \frac{1}{2}\left( \frac{\partial v}{\partial z} + \frac{\partial w}{\partial y} \right)  = \frac{1}{2} \gamma_{yz}\\
\varepsilon_{xz} &= \frac{1}{2}\left( \frac{\partial u}{\partial z} + \frac{\partial w}{\partial x} \right) = \frac{1}{2} \gamma_{xz}\\
\end{aligned}
\end{equation*}

In [3]:
import numpy as np
from sympy import diff
np.set_printoptions(precision=3, suppress=True)

print('Matriz das deformações infinitesimal, [D] :')

U = u1(c1,X,Y,Z)
V = u2(c2,X,Y,Z)
W = u3(c3,X,Y,Z)

# componentes cartesianas da matriz das deformações
exx = diff(U, X)
Nexx = exx.subs({(c1,NC1),(X,XE),(Y,YE),(Z,ZE)})
print(f'\nexx = du\\dx = {exx} = {Nexx:.5f}')
eyy = diff(V, Y)
Neyy = eyy.subs({(c2,NC2),(X,XE),(Y,YE),(Z,ZE)})
print(f'eyy = dv\\dy = {eyy} = {Neyy:.5f}')
ezz = diff(W, Z)
Nezz = ezz.subs({(c3,NC3),(X,XE),(Y,YE),(Z,ZE)})
print(f'ezz = dw\\dz = {ezz} = {Nezz:.5f}')
exy  = 0.5*(diff(U, Y) + diff(V, X))
Nexy = exy.subs({(c1,NC1),(c2,NC2),(X,XE),(Y,YE),(Z,ZE)})
print(f'exy = 1\\2 gxy = 1\\2(du\\dy+dv\\dx) = {exy} = {Nexy:.5f}')
exz  = 0.5*(diff(U, Z) + diff(W, X))
Nexz = exz.subs({(c1,NC1),(c3,NC3),(X,XE),(Y,YE),(Z,ZE)})
print(f'exz = 1\\2 gxz = 1\\2(du\\dz+dw\\dx) = {exz} = {Nexz:.5f}')
eyz  = 0.5*(diff(V, Z) + diff(W, Y) )
Neyz = eyz.subs({(c2,NC2),(c3,NC3),(X,XE),(Y,YE),(Z,ZE)})
print(f'eyz = 1\\2 gxy = 1\\2(dv\\dz+dw\\dy) = {eyz} = {Neyz:.5f}')



Matriz das deformações infinitesimal, [D] :

exx = du\dx = Y*Z*c1 = 0.00267
eyy = dv\dy = X*Z*c2 = 0.00200
ezz = dw\dz = X*Y*c3 = -0.00200
exy = 1\2 gxy = 1\2(du\dy+dv\dx) = 0.5*X*Z*c1 + 0.5*Y*Z*c2 = 0.00267
exz = 1\2 gxz = 1\2(du\dz+dw\dx) = 0.5*X*Y*c1 + 0.5*Y*Z*c3 = -0.00033
eyz = 1\2 gxy = 1\2(dv\dz+dw\dy) = 0.5*X*Y*c2 + 0.5*X*Z*c3 = -0.00150


Em forma matricial,

\begin{equation*}
\begin{aligned}
\underline{\underline{\varepsilon}} \equiv [\varepsilon] \equiv \varepsilon_{ij}
&=
\begin{bmatrix}
\varepsilon_{xx} & \varepsilon_{xy} & \varepsilon_{xz}\\
\varepsilon_{yx} & \varepsilon_{yy} & \varepsilon_{yz} \\
\varepsilon_{zx} & \varepsilon_{zy} & \varepsilon_{zz} \\
\end{bmatrix} =
\begin{bmatrix}
\varepsilon_{xx} & \gamma_{xy}/2 & \gamma_{xz}/2 \\
\gamma_{yx}/2 & \varepsilon_{yy} & \gamma_{yz}/2 \\
\gamma_{zx}/2 & \gamma_{yz}/2 & \varepsilon_{zz} \\
\end{bmatrix} \\
&=
\begin{bmatrix}
\displaystyle\frac{\partial u}{\partial x}
& \displaystyle\frac{1}{2}\left(\frac{\partial u}{\partial y} + \frac{\partial v}{\partial x} \right)
& \displaystyle\frac{1}{2}\left(\frac{\partial u}{\partial z} + \frac{\partial w}{\partial x} \right) \\
\displaystyle\frac{1}{2}\left(\frac{\partial v}{\partial x} + \frac{\partial u}{\partial y} \right)
& \displaystyle\frac{\partial v}{\partial y}
& \displaystyle\frac{1}{2}\left(\frac{\partial v}{\partial z} + \frac{\partial w}{\partial y} \right) \\
\displaystyle\frac{1}{2}\left(\frac{\partial w}{\partial x} + \frac{\partial u}{\partial z} \right)
& \displaystyle\frac{1}{2}\left(\frac{\partial v}{\partial z} + \frac{\partial w}{\partial y} \right)
& \displaystyle\frac{\partial w}{\partial z} \\
\end{bmatrix}
\end{aligned}
\end{equation*}

In [4]:
def mdef(exx,exy,exz,eyy,eyz,ezz):
    return np.array([[exx,exy,exz],[exy,eyy,eyz],[exz,eyz,ezz]])

mD0 = mdef(Nexx,Nexy,Nexz,Neyy,Neyz,Nezz)
print(f'\n[D] = \n {mD0}')


[D] = 
 [[0.00266666666666667 0.00266666666666667 -0.000333333333333333]
 [0.00266666666666667 0.00200000000000000 -0.00150000000000000]
 [-0.000333333333333333 -0.00150000000000000 -0.00200000000000000]]


#### b) Determine a deformação normal no ponto E na direcção da linha EA.   <a name="B"></a>

([enunciatum](#PII58))

Considere-se um eixo ordenado ao longo da linha $\vec{EA}$. O versor da
direção pode ser obtido por:

\begin{equation*}
\begin{aligned}
&A=(1,5;\,0;\,0) \quad E=(1,5;\,1,0;\,2,0) \\
&\vec{EA} = A - E = (0;\,-1;\,-2) \\
&||\vec{EA}|| = \sqrt{\vec{EA}\cdot\vec{EA}}
= 2.236 \\
&\vec{n}_{EA} = \frac{\vec{EA}}{||\vec{EA}||}
= \left(0;\,-\frac{1}{\sqrt{5}};\,
-\frac{2}{\sqrt{5}}\right)
\end{aligned}
\end{equation*}

In [5]:
pA = [XE,0,0]  # list
pE = [XE,YE,ZE]

vetEA = np.array(pA) - np.array(pE)
print(f'vetor  EA = {vetEA}')
normEA = np.sqrt(np.dot(vetEA,vetEA))
print(f'norma  EA = {normEA:.3f}')
nEA = vetEA/normEA
print(f'versor EA = {nEA}')

vetor  EA = [ 0. -1. -2.]
norma  EA = 2.236
versor EA = [ 0.    -0.447 -0.894]


A extensão ou deformação normal na direção definida pelo vetor $\vec{EA}$ vem:

\begin{equation*}
\varepsilon^{(\vec{n}_{EA})} = \underline{n}_{EA}^\top
\,\underline{\underline{D}}\,\underline{n}_{EA}
= \{n_{EA}\}^\top [D] \{n_{EA}\}
\end{equation*}

ou seja,

\begin{equation*}
\varepsilon(P,\vec{n}) = \varepsilon_{xx}l_1^2 + \varepsilon_{yy}m_1^2 + \varepsilon_{zz}n_1^2 +
\gamma_{xy}l_1m_1 + \gamma_{xz}l_1n_1 + \gamma_{yz}m_1n_1
\end{equation*}

onde os cossenos diretores estão associados à direção do vetor $\vec{EA}$: $(l_1, m_1, n_1) =$ $(l_{AE}, m_{AE}, n_{AE})$ $= (0, -1/\sqrt{5},-2/\sqrt{5})$. De onde resulta,

\begin{equation*}
\begin{aligned}
\varepsilon(E,\vec{n}_{EA}) &= \varepsilon_{yy}m_{EA}^2 +
\varepsilon_{zz}n_{EA}^2 + \gamma_{yz}m_{EA}n_{EA} \\
&= \frac{0.002}{5} - \frac{0.002(4)}{5} - \frac{0.003(2)}{5} \\
&= -0.0024
\end{aligned}
\end{equation*}

In [6]:
epsE_EA = np.dot(np.transpose(nEA),np.dot(mD0,nEA))
print('epsE_EA = ','{:.5f}'.format(epsE_EA))

def deflinear(exx,eyy,ezz,gxy,gxz,gyz,l,m,n):
    return exx*l**2 + eyy*m**2 + ezz*n**2 + gxy*l*m + gxz*l*n + gyz*m*n

l1, m1, n1 = nEA[0], nEA[1], nEA[2]

epsE_EA_exp = deflinear(Nexx,Neyy,Nezz,2*Nexy,2*Nexz,2*Neyz,l1,m1,n1)
print(f'eps(E, n(EA) (eq.) = {epsE_EA_exp:.5f}')

epsE_EA =  -0.00240
eps(E, n(EA) (eq.) = -0.00240


#### c) Qual o valor da distorção no plano definido pelos versores das direções das linhas EA e EF?  <a name="C"></a>

([enunciatum](#PII58))

Considerando os cossenos diretores dos versores das direções dos vetores $\vec{EA}$ ($\vec{n}_1$) e $\vec{EF}$ ($\vec{n}_2$), a distorção angular entre as duas direções (inicialmente ortogonais entre) é dada por:

\begin{equation*}
\begin{aligned}
\gamma_{12}(P,\vec{n}_1,\vec{n}_2) &= 2 \{n\}_1^T [D]\{n\}_2 \\
&= 2\varepsilon_{xx}l_1l_2 + 2\varepsilon_{yy}m_1m_2 + 2\varepsilon_{zz}n_1n_2 + \gamma_{xy}(l_1m_2 + l_2m_1)
+ \gamma_{xz}(l_1n_2 + l_2n_1) + \gamma_{yz}(m_1n_2 + m_2n_1)
\end{aligned}
\end{equation*}

ou seja,

\begin{equation*}
\begin{aligned}
\gamma_{12}(E,\vec{n}_{EA},\vec{n}_{EF}) &=
2 \{n\}_{EA}^\top [D]\{n\}_{EF} \\
&= 2\varepsilon_{xx}l_1l_2 + 2\varepsilon_{yy}m_1m_2 + 2\varepsilon_{zz}n_1n_2 + \gamma_{xy}(l_1m_2 + l_2m_1)
+ \gamma_{xz}(l_1n_2 + l_2n_1) + \gamma_{yz}(m_1n_2 + m_2n_1)
\end{aligned}
\end{equation*}

In [10]:
pF = [0,YE,ZE]

vetEF = np.array(pF) - np.array(pE)
print(f'vetor EF = {vetEF}')
normEF = np.sqrt(np.dot(vetEF,vetEF))
print(f'norma EF = {normEF}')
nEF = vetEF/normEF
print(f'versor EF = {nEF}')

gammaE_EAEF = 2*np.dot(np.transpose(nEA),np.dot(mD0,nEF))
print(f'gammaE_EAEF (v1)  = {gammaE_EAEF:.5f}')

gammaE_EAEF_v2 = 2*np.dot(np.transpose(nEF),np.dot(mD0,nEA))
print(f'gammaE_EAEF (v2)  = {gammaE_EAEF_v2:.5f}')

def defangular(exx,eyy,ezz,gxy,gxz,gyz,l1,m1,n1,l2,m2,n2):
    return 2*exx*l1*l2 + 2*eyy*m1*m2 + 2*ezz*n1*n2 + gxy*(l1*m2 + l2*m1) + gxz*(l1*n2 + l2*n1) + gyz*(m1*n2 + m2*n1)

l2, m2, n2 = nEF[0], nEF[1], nEF[2]

gammaE_EAEF_eq = defangular(Nexx,Neyy,Nezz,2*Nexy,2*Nexz,2*Neyz,l1,m1,n1,l2,m2,n2)
print(f'gammaE_EAEF (eq.) = {gammaE_EAEF_eq:.5f}')

vetor EF = [-1.5  0.   0. ]
norma EF = 1.5
versor EF = [-1.  0.  0.]
gammaE_EAEF (v1)  = 0.00179
gammaE_EAEF (v2)  = 0.00179
gammaE_EAEF (eq.) = 0.00179


---

Copyright (c) [Mecânica dos Sólidos I - DEMI - NOVA-SST]

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>

