<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/iLogos/nsst.jpg" width="400" height="100">

# DEMI | NOVA SST

## Mecânica dos Sólidos I

# III. Materiais elásticos
## Lei de Hooke. Parte II
## Problema 4 <a name="PIII74"></a>

Considere uma barra prismática de secção rectangular (10 $\times$ 15 cm) e 200 cm de comprimento. A barra é feita de alumínio, com $E = 70$ GPa e $\nu= 0,3 $ e está sujeita a uma força axial de compressão de 2 kN, como indicado na Figura.

[a)](#A) Escreva as relações que exprimem a lei de Hooke generalizada.

[b)](#B) Calcule o tensor das deformações num ponto da face mais larga, assumindo que a distribuição de tensões é constante ao longo de toda a barra.

[c)](#C) Calcule a variação de comprimento da diagonal AB na face de menor largura.

[d)](#D) Calcule a variação de comprimento da mesma diagonal da alínea c) mas admitindo agora que as faces de largura menor estão encostadas a paredes rígidas e indeformáveis.

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/Notebooks/Au07/Au07_P004_i1.jpg"
width="550" height="250">


## Resolução

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/Notebooks/Au07/Au07_P004_i2.jpg"
width="600" height="75">

#### a) Escreva as relações que exprimem a lei de Hooke generalizada.<a name="A"></a>

([enunciatum](#PIII74))


De acordo com a lei constitutiva de Hooke, as componentes cartesianas do tensor das tensões é dado em função das componentes das deformações pela seguinte expressão:

\begin{equation*}
\sigma_{ij} = \frac{E}{1+\nu}\varepsilon_{ij} + \frac{\nu E}{(1+\nu)(1-2\nu)}\varepsilon_{kk}\delta_{ij}
= 2\mu \varepsilon_{ij} + \lambda\varepsilon_{kk}\delta_{ij}
\end{equation*}

Em forma matricial, genericamente, vem:


\begin{equation*}
\begin{bmatrix}
\sigma_{11} \\ \sigma_{22} \\ \sigma_{33} \\ \tau_{23} \\  \tau_{13} \\ \tau_{12}
\end{bmatrix} = \frac{E}{(1+\nu)(1-2\nu)}
\begin{bmatrix}
1-\nu & \nu & \nu & 0 & 0 & 0 \\
\nu & 1-\nu & \nu & 0 & 0 & 0 \\
\nu & \nu & 1-\nu & 0 & 0 & 0 \\
0 & 0 & 0 & (1-2\nu)/2 & 0 & 0 \\
0 & 0 & 0 & 0 & (1-2\nu)/2 & 0 \\
0 & 0 & 0 & 0 & 0 & (1-2\nu)/2 \\
\end{bmatrix}
\begin{bmatrix}
\varepsilon_{11} \\ \varepsilon_{22} \\ \varepsilon_{33} \\ 2\varepsilon_{23} \\ 2\varepsilon_{13} \\ 2\varepsilon_{12}
\end{bmatrix}
\end{equation*}

A lei constitutiva linear elástica pode ainda ser expressa em termos das constantes de Lamé - Gabriel Lamé (22 July 1795 – 1 May 1870):

\begin{equation*}
\begin{bmatrix}
\sigma_{11} \\ \sigma_{22} \\ \sigma_{33} \\ \tau_{23} \\  \tau_{13} \\ \tau_{12}
\end{bmatrix} =
\begin{bmatrix}
\lambda + 2 \mu & \lambda & \lambda & 0 & 0 & 0 \\
\lambda & \lambda + 2 \mu & \lambda & 0 & 0 & 0 \\
\lambda & \lambda & \lambda + 2 \mu & 0 & 0 & 0 \\
0 & 0 & 0 & \mu & 0 & 0 \\
0 & 0 & 0 & 0 & \mu & 0 \\
0 & 0 & 0 & 0 & 0 & \mu \\
\end{bmatrix}
\begin{bmatrix}
\varepsilon_{11} \\ \varepsilon_{22} \\ \varepsilon_{33} \\ 2\varepsilon_{23} \\ 2\varepsilon_{13} \\ 2\varepsilon_{12}
\end{bmatrix}
\end{equation*}

com,

\begin{equation*}
\begin{aligned}
\lambda = \frac{E\nu}{(1+\nu)(1-2\nu)} , \quad \mu = G = \frac{E}{2(1+\nu)}
\end{aligned}
\end{equation*}

Neste caso não é conhecida a deformação fora do plano $\varepsilon_{zz}\equiv \varepsilon_{33}$. Desta forma é necessário resolver as equações partindo da formulação dual:

Para um material isotrópico a lei de Hooke 3D pode ser expressa por:

\begin{equation*}
\varepsilon_{ij} = \frac{1}{E}[(1+\nu)\sigma_{ij} - \nu\delta_{ij}\sigma_{kk}]
\end{equation*}

Em forma matricial a lei constitutiva linear elástica expressa em termos de módulo de Young e coeficiente de Poisson vem:

\begin{equation*}
\begin{cases}
\varepsilon_{11} &= \displaystyle\frac{\sigma_{11}}{E} - \nu\frac{\sigma_{22}}{E} - \nu\frac{\sigma_{33}}{E} \\
\varepsilon_{22} &= - \nu\displaystyle\frac{\sigma_{11}}{E} + \frac{\sigma_{22}}{E} - \nu\displaystyle\frac{\sigma_{33}}{E} \\
\varepsilon_{33} &= - \nu\displaystyle\frac{\sigma_{11}}{E} - \nu\displaystyle\frac{\sigma_{22}}{E} + \frac{\sigma_{33}}{E} \\
\gamma_{23} &= 2\varepsilon_{23} = \displaystyle\frac{\tau_{23}}{G}\\
\gamma_{13} &= 2\varepsilon_{13} = \displaystyle\frac{\tau_{13}}{G}\\
\gamma_{12} &= 2\varepsilon_{12} = \displaystyle\frac{\tau_{12}}{G}\\
\end{cases}
\end{equation*}

com,

\begin{equation*}
G = \frac{E}{2(1+\nu)}
\end{equation*}

Na forma matricial têm-se:

\begin{equation*}
\begin{bmatrix}
\varepsilon_{11} \\ \varepsilon_{22} \\ \varepsilon_{33} \\ 2\varepsilon_{23} \\ 2\varepsilon_{13} \\ 2\varepsilon_{12}
\end{bmatrix} = \frac{1}{E}
\begin{bmatrix}
1 & -\nu & -\nu & 0 & 0 & 0 \\
-\nu & 1 & -\nu & 0 & 0 & 0 \\
-\nu & -\nu & 1 & 0 & 0 & 0 \\
0 & 0 & 0 & 2(1+\nu) & 0 & 0 \\
0 & 0 & 0 & 0 & 2(1+\nu) & 0 \\
0 & 0 & 0 & 0 & 0 & 2(1+\nu) \\
\end{bmatrix}
\begin{bmatrix}
\sigma_{11} \\ \sigma_{22} \\ \sigma_{33} \\ \tau_{23} \\  \tau_{13} \\ \tau_{12}
\end{bmatrix}
\end{equation*}

#### b) Calcule o tensor das deformações num ponto da face mais larga, assumindo que a distribuição de tensões é constante ao longo de toda a barra.<a name="B"></a>

([enunciatum](#PIII74))

Do estado de compressão uniaxial e uniforme aplicado resulta:

\begin{equation*}
\sigma_{xx} = \frac{F}{A}
\end{equation*}

com,

\begin{equation*}
\underline{\underline{\sigma}} = \sigma_{ij} =
\begin{bmatrix}
F/A & 0 & 0 \\
0 & 0 & 0 \\
0 & 0 & 0 \\
\end{bmatrix}
\end{equation*}

Pela aplicação da lei de Hooke vem:

\begin{equation*}
\begin{aligned}
\varepsilon_{xx} &= \frac{\sigma_{xx}}{E} = -\frac{F}{AE} \\
\varepsilon_{yy} &= \varepsilon_{zz} = -\nu\varepsilon_{xx}= \frac{\nu F}{AE}
\end{aligned}
\end{equation*}

In [2]:
import numpy as np
from matplotlib import rcParams, rc
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 18
rc('text', usetex=True)

np.set_printoptions(precision=3)

def tt(sxx,sxy,sxz,syy,syz,szz):
    return np.array([[sxx,sxy,sxz],[sxy,syy,syz],[sxz,syz,szz]])

# dados, unidades: mm
lx, ly, lz = 2000., 100., 150.
As = ly*lz
print('Área de secção transversal do perfil = ',As,' mm^2')
F = -2000.0 # unidade: N
print('                      Força aplicada = ',F,' N')
sxx = F/As
print('                     Tensão aplicada = ','{:.3f}'.format(sxx),' MPa (=N/mm^2)')
# estado plano, uniaxial e uniforme de tensão:
sxy = sxz = syz = syy = szz = 0

mt0 = tt(sxx,sxy,sxz,syy,syz,szz)
print('Matriz das tensões = \n',mt0)

# unit: MPa
E, v = 70.*1e3, 0.3
G = E/2/(1+v)
lam, mu = (E*v)/((1+v)*(1-2*v)), G
print('Propriedades do material: ---------------')
print('     E (MPa) = ',E)
print('           v = ',v)
print('     G (MPa) = ','{:.2f}'.format(G))
print('lambda (MPa) = ','{:.2f}'.format(lam))
print('    mu (MPa) = ','{:.2f}'.format(mu))

def e11(sxx,syy,szz,E): return (sxx - v*(syy+szz))/E
def e22(sxx,syy,szz,E): return (syy - v*(sxx+szz))/E
def e33(sxx,syy,szz,E): return (szz - v*(sxx+syy))/E
def e23(syz,G): return (syz/G)/2
def e13(sxz,G): return (sxz/G)/2
def e12(sxy,G): return (sxy/G)/2

exx = e11(sxx,syy,szz,E)
eyy = e22(sxx,syy,szz,E)
ezz = e22(sxx,syy,szz,E)
gyz = gxz = gxy = 0
eyz = 2*gyz; exz = 2*gxz; exy = 2*gxy

def td(exx,exy,exz,eyy,eyz,ezz):
    return np.array([[exx,exy,exz],[exy,eyy,eyz],[exz,eyz,ezz]])

np.set_printoptions(formatter={'float': '{: 0.5f}'.format})
md0 = td(exx,exy,exz,eyy,eyz,ezz)
print('Matriz das deformações = \n',md0*1e6,'micro-def')

Área de secção transversal do perfil =  15000.0  mm^2
                      Força aplicada =  -2000.0  N
                     Tensão aplicada =  -0.133  MPa (=N/mm^2)
Matriz das tensões = 
 [[-0.133  0.     0.   ]
 [ 0.     0.     0.   ]
 [ 0.     0.     0.   ]]
Propriedades do material: ---------------
     E (MPa) =  70000.0
           v =  0.3
     G (MPa) =  26923.08
lambda (MPa) =  40384.62
    mu (MPa) =  26923.08
Matriz das deformações = 
 [[-1.90476  0.00000  0.00000]
 [ 0.00000  0.57143  0.00000]
 [ 0.00000  0.00000  0.57143]] micro-def


#### c) Calcule a variação de comprimento da diagonal AB na face de menor largura.<a name="C"></a>

([enunciatum](#PIII74))

A medição de um extensómetro orientado de um determinado ângulo $\theta$ em relação ao eixo horizontal vem expressa em função das componentes do tensor das deformações por:

\begin{equation*}
\varepsilon(\theta) \equiv \varepsilon_\mathrm{AB} = \varepsilon_{xx}\cos^2\theta + \varepsilon_{yy}\sin^2\theta + \gamma_{xy}\sin\theta\cos\theta
\end{equation*}

Pelo que a variação em comprimento do segmento $AB$ pode ser obtida de acordo com a definição de deformação linear:

\begin{equation*}
\varepsilon_\mathrm{AB} = \frac{\Delta L_\mathrm{AB}}{L_\mathrm{AB}} \quad\vee
\quad l_f=l_0(1+\varepsilon) \quad\wedge\quad L_\mathrm{AB} = \sqrt{l_x²+l_y²}
 \quad\wedge\quad \theta = \arctan{\left(\frac{l_y}{l_x}\right)}
\end{equation*}

ou seja,

\begin{equation*}
\Delta L_\mathrm{AB}  = (\varepsilon_{xx}\cos^2\theta + \varepsilon_{yy}\sin^2\theta + \gamma_{xy}\sin\theta\cos\theta )L_\mathrm{AB}
\end{equation*}

atendendo a que $\gamma_{ij} = 0$,

\begin{equation*}
\Delta L_\mathrm{AB}  = (\varepsilon_{xx}\cos^2\theta_\mathrm{AB} +
\varepsilon_{yy}\sin^2\theta_\mathrm{AB} )L_\mathrm{AB}
\end{equation*}

In [3]:
LAB = np.sqrt(lx**2 + ly**2)
print('Comprimento AB = ','{:.2f}'.format(LAB),' mm')
theta = np.arctan(ly/lx)
print('Ângulo segmento AB em relação à horizontal = ','{:.3f}'.format(np.rad2deg(theta)),' deg')

def extensometro(eXX,eYY,gXY,t):
    return eXX*np.cos(t)**2 +  eYY*np.sin(t)**2 + gXY*np.sin(t)*np.cos(t)

eAB = extensometro(exx,eyy,2*exy,theta)
print('ext AB = ','{:.4f}'.format(eAB*1e6),'micro-def')

DLAB = eAB*LAB
print('D AB = ','{:.4e}'.format(DLAB),'mm | ','{:.3f}'.format(DLAB*1e3),' microns' )

Comprimento AB =  2002.50  mm
Ângulo segmento AB em relação à horizontal =  2.862  deg
ext AB =  -1.8986 micro-def
D AB =  -3.8019e-03 mm |  -3.802  microns


Transformação do tensor das deformações:

\begin{equation*}
[\varepsilon]_1 = [Q_{01}]\,[\varepsilon]_0[Q_{01}]^\mathrm{T}
\end{equation*}

Explicitamente,

\begin{equation*}
\begin{aligned}
\begin{bmatrix}
\varepsilon_{x'x'} & \varepsilon_{x'y'} & \varepsilon_{x'z'}\\
\varepsilon_{y'y'} & \varepsilon_{y'y'} & \varepsilon_{y'z'}\\
\varepsilon_{z'y'} & \varepsilon_{z'y'} & \varepsilon_{z'z'}\\
\end{bmatrix} &=
\begin{bmatrix}
l_1 & m_1 & n_1 \\
l_2 & m_2 & n_2 \\
l_3 & m_3 & n_3 \\
\end{bmatrix}
\begin{bmatrix}
\varepsilon_{xx} & \varepsilon_{xy} & \varepsilon_{xz} \\
\varepsilon_{yx} & \varepsilon_{yy} & \varepsilon_{yz} \\
\varepsilon_{zx} & \varepsilon_{zy} & \varepsilon_{zz} \\
\end{bmatrix}
\begin{bmatrix}
l_1 & l_2 & l_3 \\
m_1 & m_2 & m_3 \\
n_1 & n_2 & n_3 \\
\end{bmatrix}
\\
&=
\begin{bmatrix}
\cos\theta & \sin\theta & 0\\
-\sin\theta  & \cos\theta & 0\\
0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
\varepsilon_{xx} & \varepsilon_{xy} & \varepsilon_{xz} \\
\varepsilon_{yx} & \varepsilon_{yy} & \varepsilon_{yz} \\
\varepsilon_{zx} & \varepsilon_{zy} & \varepsilon_{zz} \\
\end{bmatrix}
\begin{bmatrix}
\cos\theta & -\sin\theta & 0 \\
\sin\theta  & \cos\theta & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\end{aligned}
\end{equation*}

In [4]:
print('-----------------------------------------------')
print('Versão 2:')
print('-----------------------------------------------')
def Q(ang,rot):
    c = np.cos(ang)
    s = np.sin(ang)
    if rot == 1:
        Qij = np.array([[1,0,0],[0,c,s],[0,-s,c]])
    elif rot == 2:
        Qij = np.array([[c,0,s],[0,1,0],[-s,0,c]])
    else:
        Qij = np.array([[c,s,0],[-s,c,0],[0,0,1]])
    return Qij

mT = Q(theta,3)
print(' mT2D = \n',mT)
#md02D = md0[0:2,0:2]
#print('md02D = \n',md02D)
np.set_printoptions(formatter={'float': '{: 0.5f}'.format})
mdAB = np.dot(mT,np.dot(md0,np.transpose(mT)))
print(' mdAB = \n',mdAB*1e6,'micro-def')

eABv2 = mdAB[0,0]
print('ext AB = ','{:.4f}'.format(eABv2*1e6),'micro-def')

DLABv2 = eABv2*LAB
print('D AB = ','{:.4e}'.format(DLABv2),'mm | ','{:.3f}'.format(DLABv2*1e3),' microns' )

-----------------------------------------------
Versão 2:
-----------------------------------------------
 mT2D = 
 [[ 0.99875  0.04994  0.00000]
 [-0.04994  0.99875  0.00000]
 [ 0.00000  0.00000  1.00000]]
 mdAB = 
 [[-1.89859  0.12350  0.00000]
 [ 0.12350  0.56525  0.00000]
 [ 0.00000  0.00000  0.57143]] micro-def
ext AB =  -1.8986 micro-def
D AB =  -3.8019e-03 mm |  -3.802  microns


É possível mostrar que a deformação linear numa determinada direção, $\vec{n}$, definida pelos cosenos diretores $l,m, n$ (ou $n_x,n_y,n_z$) é dada pela seguinte expressão de transformação em relação às componentes da matriz de deformação em relação a um dado referencial:

\begin{equation*}
\begin{aligned}
\varepsilon(\vec{n}) = \{n\}^T[\varepsilon]\{n\}
&=  \varepsilon_{xx} l^2 + \varepsilon_{yy}m^2 + \varepsilon_{zz}n^2
+ \varepsilon_{xy}lm + \varepsilon_{yz}mn + \varepsilon_{xz}ln \\
& =  \varepsilon_{xx} n_x^2 + \varepsilon_{yy}n_y^2 + \varepsilon_{zz}n_z^2
+ \varepsilon_{xy}n_xn_y + \varepsilon_{yz}n_yn_z + \varepsilon_{xz}n_xn_z
\end{aligned}
\end{equation*}

In [5]:
print('-----------------------------------------------')
print('Versão 3:')
print('-----------------------------------------------')

nx = np.cos(theta)
ny = np.sin(theta)
nz = 0
nvec = np.array([nx,ny,nz])
print('versor n AB = \n',nvec,' | norma: ','{:.2f}'.format(np.sqrt(np.dot(nvec,nvec))))
def epsn(exx,eyy,ezz,exy,eyz,exz,nx,ny,nz):
    return exx*nx**2 + eyy*ny**2 + ezz*nz**2 + exy*nx*ny + eyz*ny*nz + exz*nx*nz

epsnAB = epsn(exx,eyy,ezz,exy,eyz,exz,nx,ny,nz)
print('ext AB = ','{:.4f}'.format(epsnAB*1e6),'micro-def')

DLABvecn = epsnAB*LAB
print('D AB = ','{:.4e}'.format(DLABvecn),'mm | ','{:.3f}'.format(DLABvecn*1e3),' microns' )

-----------------------------------------------
Versão 3:
-----------------------------------------------
versor n AB = 
 [ 0.99875  0.04994  0.00000]  | norma:  1.00
ext AB =  -1.8986 micro-def
D AB =  -3.8019e-03 mm |  -3.802  microns


#### d) Calcule a variação de comprimento da mesma diagonal da alínea c) mas admitindo agora que as faces de largura menor estão encostadas a paredes rígidas e indeformáveis.<a name="D"></a>

([enunciatum](#PIII74))

A condição de paredes rígidas e indeformáveis impõe, no plano de secção $y-z$, as seguintes relações:

\begin{equation*}
\varepsilon_{zz} = 0 \quad \wedge \sigma_{zz} \ne 0
\end{equation*}

Assim sendo, a tensão uniaxial e uniforme aplicada, $\sigma_{xx}$, irá introduzir uma tensão normal segundo o eixo dos $zz$ dada por:

\begin{equation*}
\begin{aligned}
\varepsilon_{zz} &= - \nu\displaystyle\frac{\sigma_{xx}}{E} - \nu\displaystyle\frac{\sigma_{yy}}{E} + \frac{\sigma_{zz}}{E} \\
0 &= - \nu\displaystyle\frac{\sigma_{xx}}{E} + \frac{\sigma_{zz}}{E} \\
\Leftrightarrow \sigma_{zz} &= \nu\sigma_{xx} = \nu\frac{F}{A}
\end{aligned}
\end{equation*}

In [6]:
szz = v*sxx
print('Tensão sigma zz = ','{:.3f}'.format(szz),' MPa (=N/mm^2)')

# recalculando o estado de deformação para a tensão aplicada
exx = e11(sxx,syy,szz,E)
eyy = e22(sxx,syy,szz,E)
ezz = e22(sxx,syy,szz,E)
gyz = gxz = gxy = 0
eyz = 2*gyz; exz = 2*gxz; exy = 2*gxy

np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
md0d = td(exx,exy,exz,eyy,eyz,ezz)
print('Matriz das deformações d) = \n',md0d*1e6,'micro-def')

eABd = extensometro(exx,eyy,2*exy,theta)
print('ext AB d) = ','{:.4f}'.format(eABd*1e6),'micro-def')

DLABd = eABd*LAB
print('D ABd = ','{:.4e}'.format(DLABd),'mm | ','{:.3f}'.format(DLABd*1e3),' microns' )

Tensão sigma zz =  -0.040  MPa (=N/mm^2)
Matriz das deformações d) = 
 [[-1.733  0.000  0.000]
 [ 0.000  0.743  0.000]
 [ 0.000  0.000  0.743]] micro-def
ext AB d) =  -1.7272 micro-def
D ABd =  -3.4586e-03 mm |  -3.459  microns


In [7]:
print('-----------------------------------------------')
print('Versão 2:')
print('-----------------------------------------------')

np.set_printoptions(formatter={'float': '{: 0.5f}'.format})
mdABdv2 = np.dot(mT,np.dot(md0d,np.transpose(mT)))
print(' mdAB = \n',mdABdv2*1e6,'micro-def')

eABdv2 = mdABdv2[0,0]
print('ext AB = ','{:.4f}'.format(eABdv2*1e6),'micro-def')

DLABdv2 = eABdv2*LAB
print('D AB = ','{:.4e}'.format(DLABdv2),'mm | ','{:.3f}'.format(DLABdv2*1e3),' microns' )

-----------------------------------------------
Versão 2:
-----------------------------------------------
 mdAB = 
 [[-1.72716  0.12350  0.00000]
 [ 0.12350  0.73668  0.00000]
 [ 0.00000  0.00000  0.74286]] micro-def
ext AB =  -1.7272 micro-def
D AB =  -3.4586e-03 mm |  -3.459  microns


---

Copyright (c) [Mecânica dos Sólidos I - DEMI - NOVA-SST]

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>
