<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/iLogos/nsst.jpg" width="400" height="100">

# DEMI | NOVA SST

## Mecânica dos Sólidos I

# III. Materiais elásticos
## Lei de Hooke. Parte II
## Problema 5 <a name="PIII75"></a>

Considere o paralelepípedo representado na Figura. Duas das faces suportam a tensão $\sigma_1$, como indicado, enquanto outras duas (superior e inferior) estão em contacto com superfícies rígidas, planas e sem atrito e as duas restantes estão livres. O módulo de elasticidade transversal e o coeficiente de Poisson do material são 210 GPa e 0,28 respectivamente.

[a)](#A) Determine a intensidade de $\sigma_1$ sabendo que depois de aplicar esta tensão a dimensão transversal passa de 20 mm para 20,004 mm.

[b)](#B) Determine o tensor das tensões e o tensor das deformações para um ponto genérico do paralelepípedo.

[c)](#C) Calcule a variação de comprimento da diagonal representada na Figura.



## Resolução

<img src="https://userweb.fct.unl.pt/~jmc.xavier/MSI/Notebooks/Au07/Au07_P005_i1.jpg"
width="400" height="120">

#### a) Determine a intensidade de $\sigma_1$ sabendo que depois de aplicar esta tensão a dimensão transversal passa de 20 mm para 20,004 mm.<a name="A"></a>

([enunciatum](#PIII75))

Atendendo à definição de extensão linear: $\varepsilon_{yy} = \Delta L_y/L_y = 0,004/20 = 0,0002 $

A superfície lateral perpendicular ao eixos coordenado dos $yy$ é uma superfície livre pelo que $\sigma_{yy}=0$. Por outro lado, devido ao encastramento da superfície lateral na direção do eixo dos $zz$ têm-se: $\varepsilon_{zz} = 0$. Com estes dados de entrada, pode-se escrever o seguinte sistema de equações a partir da lei connstitutiva de Hooke:*

\begin{equation*}
\begin{cases}
\varepsilon_{yy} = \displaystyle\frac{\Delta L_y}{L_y} = 0,0002 \\
\varepsilon_{zz} = 0
\end{cases} \Leftrightarrow
\begin{cases}
\varepsilon_{yy} = \displaystyle\frac{\sigma_{yy}}{E} -
\displaystyle\frac{\nu}{E}(\sigma_{xx} + \sigma_{zz}) = \displaystyle\frac{\Delta L_y}{L_y} = 0,0002 \\
\varepsilon_{zz} = \displaystyle\frac{\sigma_{zz}}{E} -
\displaystyle\frac{\nu}{E}(\sigma_{xx} + \sigma_{yy}) = 0
\end{cases}
\end{equation*}

de onde se obtem:

\begin{equation*}
\begin{cases}
\sigma_{xx} = -\displaystyle\frac{E}{\nu(1+\nu)}\varepsilon_{yy} \\
\sigma_{zz} = \nu\sigma_{xx} = -\displaystyle\frac{E}{(1+\nu)}\varepsilon_{yy}
\end{cases}
\end{equation*}

In [1]:
import numpy as np
from sympy.solvers import solve
from sympy import symbols
from matplotlib import rcParams, rc
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 18
#rc('text', usetex=True)

E = 210*1e3 # unit: MPa
v = 0.28
G = E/2/(1+v)
lam = (E*v)/((1+v)*(1-2*v))
mu = G
K = E/3/(1-2*v)
print('Propriedades do material: ---------------')
print('     E (MPa) = ',E)
print('           v = ',v)
print(f'     G (MPa) = {G:.2f}')
print(f'lambda (MPa) = {lam:.2f}')
print(f'    mu (MPa) = {mu:.2f}')
print(f'     K (MPa) = {K:.2f}')

# Dados, unidades: mm
Lx, Ly, Lz, Lyf = 60, 20, 30, 20.004

DLy = Lyf - Ly
print(f'DLy = {DLy:.4f} mm')

eyyP = DLy/Ly
print(f'eyy = {eyyP*1e6:.1f} micro-def')

# Condições de fronteira
ezzP = 0 # encastramento
syyP = 0 # bordo livre

sxx,szz = symbols('sxx szz')

def e11(sxx,syy,szz,E,v): return (sxx - v*(syy+szz))/E
def e22(sxx,syy,szz,E,v): return (syy - v*(sxx+szz))/E
def e33(sxx,syy,szz,E,v): return (szz - v*(sxx+syy))/E

ex1 = eyyP - e22(sxx,syyP,szz,E,v)
ex2 = ezzP - e33(sxx,syyP,szz,E,v)

tens1 = solve({ex1,ex2},{sxx,szz})
sxxP = float(tens1[sxx])
print(f'Sxx(P) = {sxxP:.3f} MPa')
szzP = float(tens1[szz])
print(f'Szz(P) = {szzP:.3f} MPa')

Propriedades do material: ---------------
     E (MPa) =  210000.0
           v =  0.28
     G (MPa) = 82031.25
lambda (MPa) = 104403.41
    mu (MPa) = 82031.25
     K (MPa) = 159090.91
DLy = 0.0040 mm
eyy = 200.0 micro-def
Sxx(P) = -117.188 MPa
Szz(P) = -32.813 MPa


#### b) Determine o tensor das tensões e o tensor das deformações para um ponto genérico do paralelepípedo.<a name="B"></a>

([enunciatum](#PIII75))

O estado de tensão e o estado de deformação são assumidos uniformes ao longo do corpo paralelipípedo. Pelo que, a matriz de tensão no referncial $S_0(x,y,z)$ num ponto genérico do corpo é:

\begin{equation*}
\underline{\underline{\sigma}} = \sigma_{ij} =
\begin{bmatrix}
\sigma_{xx} & 0 & 0\\
0 & 0 & 0\\
0 & 0 & \sigma_{zz}\\
\end{bmatrix}
\end{equation*}

A matriz de deformação no referncial $S_0(x,y,z)$ num ponto genérico do objeto é:

\begin{equation*}
\underline{\underline{\varepsilon}} = \varepsilon_{ij} =
\begin{bmatrix}
\varepsilon_{xx} & 0 & 0\\
0 & \varepsilon_{yy} & 0\\
0 & 0 & 0\\
\end{bmatrix}
\quad\wedge\quad
\varepsilon_{xx} = \displaystyle\frac{1}{E}[\sigma_{xx} - \nu\sigma_{zz}] = 0
\end{equation*}

In [8]:
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
mt0 = np.array([[sxxP,0,0],[0,0,0],[0,0,szzP]])
print('mt0 = \n',mt0,' (MPa)')

exxP = e11(sxxP,syyP,szzP,E,v)
print(f'\nexx(P) = {exxP*1e6:.3f} micro-def')

np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
exyP = 0; exzP = 0; eyzP = 0
md0 = np.array([[exxP,exyP,exzP],[exyP,eyyP,eyzP],[exzP,eyzP,ezzP]])
print('\nmd0 = \n',md0*1e6)

mt0 = 
 [[-117.2  0.0  0.0]
 [ 0.0  0.0  0.0]
 [ 0.0  0.0 -32.8]]  (MPa)

exx(P) = -514.286 micro-def

md0 = 
 [[-514.286  0.000  0.000]
 [ 0.000  200.000  0.000]
 [ 0.000  0.000  0.000]]


#### c) Calcule a variação de comprimento da diagonal representada na Figura.<a name="C"></a>

([enunciatum](#PIII75))

É possível mostrar que a deformação linear numa determinada direção, $\vec{n}$, definida pelos cosenos diretores $l,m,n$ (ou: $n_x,n_y,n_z$) é dada pela seguinte expressão de transformação em relação às componentes da matriz de deformação em relação a um dado referencial:

\begin{equation*}
\begin{aligned}
\varepsilon(\vec{n}) & =
\varepsilon_{xx}l^2 + \varepsilon_{yy}m^2 + \varepsilon_{zz}n^2
+ \varepsilon_{xy}lm + \varepsilon_{yz}mn + \varepsilon_{xz}ln\\
& = \varepsilon_{xx} n_x^2 + \varepsilon_{yy}n_y^2 + \varepsilon_{zz}n_z^2
+ \varepsilon_{xy}n_xn_y + \varepsilon_{yz}n_yn_z + \varepsilon_{xz}n_xn_z
\end{aligned}
\end{equation*}

Se a direção $\vec{n}$ dizer um determinado ângulo $\theta$ em relação ao eixo horizontal dos $xx$ então a lei de transformação pode ser dada por:

\begin{equation*}
\varepsilon(\theta) = \varepsilon_{xx}\cos^2\theta + \varepsilon_{zz}\sin^2\theta + \gamma_{xz}\sin\theta\cos\theta
\end{equation*}

Pelo que a variação em comprimento do segmento $AB$ pode ser obtida de acordo com a definição de deformação linear:

\begin{equation*}
\varepsilon(\theta) = \frac{\Delta L}{L}
\end{equation*}

ou seja,

\begin{equation*}
\Delta L = (\varepsilon_{xx}\cos^2\theta + \varepsilon_{zz}\sin^2\theta + \gamma_{xz}\sin\theta\cos\theta )L
\end{equation*}

In [17]:
theta = np.arctan(Lz/Lx)
print(f'Ângulo segmento AB em relação à horizontal = {np.rad2deg(theta):.2f} deg')

Ldiag = np.sqrt(Lx**2 + Lz**2)
print(f'Comprimento inicial da diagonal = {Ldiag:.2f} mm')

print('-----------------------------------------------')
print('Versão 1:')
print('-----------------------------------------------')

def extensometro(e11,e22,g12,t):
    return e11*np.cos(t)**2 +  e22*np.sin(t)**2 + g12*np.sin(t)*np.cos(t)

ediag1  = extensometro(exxP,ezzP,2*exzP,theta)
print(f'ext diagonal = {ediag1*1e6:.2f} micro-def')

DLdiag1 = ediag1*Ldiag
print(f'DL diagonal = {DLdiag1:.4e} mm | {DLdiag1*1e3:.3f} microns' )

Ângulo segmento AB em relação à horizontal = 26.57 deg
Comprimento inicial da diagonal = 67.08 mm
-----------------------------------------------
Versão 1:
-----------------------------------------------
ext diagonal = -411.43 micro-def
DL diagonal = -2.7599e-02 mm | -27.599 microns


Por outro lado, pela lei de transformação de um tensor de segunda ordem, a transformação do tensor das deformações vem:

\begin{equation*}
[\varepsilon]_1 = [Q_{01}]\,[\varepsilon]_0 [Q_{01}]^\mathrm{T}
\end{equation*}

Explicitamente,

\begin{equation*}
\begin{aligned}
\begin{bmatrix}
\varepsilon_{x'x'} & \varepsilon_{x'y'} & \varepsilon_{x'z'}\\
\varepsilon_{y'y'} & \varepsilon_{y'y'} & \varepsilon_{y'z'}\\
\varepsilon_{z'y'} & \varepsilon_{z'y'} & \varepsilon_{z'z'}\\
\end{bmatrix} &=
\begin{bmatrix}
l_1 & m_1 & n_1 \\
l_2 & m_2 & n_2\\
l_3 & m_3 & n_3 \\
\end{bmatrix}
\begin{bmatrix}
\varepsilon_{xx} & \varepsilon_{xy} & \varepsilon_{xz} \\
\varepsilon_{yx} & \varepsilon_{yy} & \varepsilon_{yz} \\
\varepsilon_{zx} & \varepsilon_{zy} & \varepsilon_{zz} \\
\end{bmatrix}
\begin{bmatrix}
l_1 & l_2 & l_3 \\
m_1 & m_2 & m_3\\
n_1 & n_2 & n_3 \\
\end{bmatrix} \\
& =
\begin{bmatrix}
\cos\theta & 0 & \sin\theta\\
0  & 1 & 0\\
-\sin\theta & 0 & \cos\theta \\
\end{bmatrix}
\begin{bmatrix}
\varepsilon_{xx} & \varepsilon_{xy} & \varepsilon_{xz} \\
\varepsilon_{yx} & \varepsilon_{yy} & \varepsilon_{yz} \\
\varepsilon_{zx} & \varepsilon_{zy} & \varepsilon_{zz} \\
\end{bmatrix}
\begin{bmatrix}
\cos\theta & 0 & -\sin\theta\\
0  & 1 & 0\\
\sin\theta & 0 & \cos\theta \\
\end{bmatrix}
\end{aligned}
\end{equation*}

portanto,

\begin{equation*}
\Delta L = \varepsilon_{x'x'} L
\end{equation*}


In [18]:
print('-----------------------------------------------')
print('Versão 2:')
print('-----------------------------------------------')
def Q(ang,rot):
    c, s = np.cos(ang), np.sin(ang)
    if rot == 1:
        Qij = np.array([[1,0,0],[0,c,s],[0,-s,c]])
    elif rot == 2:
        Qij = np.array([[c,0,s],[0,1,0],[-s,0,c]])
    else:
        Qij = np.array([[c,s,0],[-s,c,0],[0,0,1]])
    return Qij

mT = Q(theta,2)
print(' mT = \n',mT)
np.set_printoptions(formatter={'float': '{: 0.5f}'.format})
md0diag = np.dot(mT,np.dot(md0,np.transpose(mT)))
print(' mat def diagonal = \n',md0diag*1e6,'micro-def')

ediag2  = md0diag[0,0]
print(f'ext diagonal = {ediag2*1e6:.4f} micro-def')
DLdiag2 = ediag2*Ldiag
print(f'DL diagonal = {DLdiag2:.4e} mm | {DLdiag2*1e3:.3f} microns')

-----------------------------------------------
Versão 2:
-----------------------------------------------
 mT = 
 [[ 0.894  0.000  0.447]
 [ 0.000  1.000  0.000]
 [-0.447  0.000  0.894]]
 mat def diagonal = 
 [[-411.42857  0.00000  205.71429]
 [ 0.00000  200.00000  0.00000]
 [ 205.71429  0.00000 -102.85714]] micro-def
ext diagonal = -411.4286 micro-def
DL diagonal = -2.7599e-02 mm | -27.599 microns


In [19]:
print('-----------------------------------------------')
print('Versão 3:')
print('-----------------------------------------------')
nx, ny, nz = np.cos(theta), 0, np.sin(theta)
nvec = np.array([nx,ny,nz])
print('versor n AB = \n',nvec,' | norma: ','{:.2f}'.format(np.sqrt(np.dot(nvec,nvec))))

def epsn(exx,eyy,ezz,exy,eyz,exz,nx,ny,nz):
    return exx*nx**2 + eyy*ny**2 + ezz*nz**2 + exy*nx*ny + eyz*ny*nz + exz*nx*nz

ediag3 = epsn(exxP,eyyP,ezzP,exyP,eyzP,exzP,nx,ny,nz)
print('ext diagonal = ','{:.4f}'.format(ediag3*1e6),'micro-def')
print('Comprimento final da diagonal =  ','{:.4f}'.format((1+ediag3)*Ldiag),' mm')
DLdiag3 = ediag3*Ldiag
print('DL diagonal = ','{:.4e}'.format(DLdiag3),'mm | ','{:.3f}'.format(DLdiag3*1e3),' microns' )

-----------------------------------------------
Versão 3:
-----------------------------------------------
versor n AB = 
 [ 0.89443  0.00000  0.44721]  | norma:  1.00
ext diagonal =  -411.4286 micro-def
Comprimento final da diagonal =   67.0544  mm
DL diagonal =  -2.7599e-02 mm |  -27.599  microns


In [6]:
print('-----------------------------------------------')
print('Versão 4:')
print('-----------------------------------------------')
LdiagF1 = Ldiag*(1+ediag3)
print('Comprimento final da diagonal =  ','{:.4f}'.format(LdiagF1),' mm')
DLdiag4 = LdiagF1 - Ldiag
print('DL diagonal = ','{:.4e}'.format(DLdiag4),'mm | ','{:.3f}'.format(DLdiag4*1e3),' microns' )

-----------------------------------------------
Versão 4:
-----------------------------------------------
Comprimento final da diagonal =   67.0544  mm
DL diagonal =  -2.7599e-02 mm |  -27.599  microns


In [7]:
print('-----------------------------------------------')
print('Versão 5:')
print('-----------------------------------------------')
LxF = Lx*(1+exxP)
LzF = Lz*(1+ezzP)
print('Comprimento final de Lx =  ','{:.4f}'.format(LxF),' mm')
print('Comprimento final de Lz =  ','{:.4f}'.format(LzF),' mm')
LdiagF2 = np.sqrt(LxF**2 + LzF**2)
print('Comprimento final da diagonal =  ','{:.4f}'.format(LdiagF2),' mm')
DLdiag5 = LdiagF2 - Ldiag
print('DL diagonal = ','{:.4e}'.format(DLdiag5),'mm | ','{:.3f}'.format(DLdiag5*1e3),' microns' )

-----------------------------------------------
Versão 5:
-----------------------------------------------
Comprimento final de Lx =   59.9691  mm
Comprimento final de Lz =   30.0000  mm
Comprimento final da diagonal =   67.0544  mm
DL diagonal =  -2.7598e-02 mm |  -27.598  microns


---

Copyright (c) [Mecânica dos Sólidos I - DEMI - NOVA-SST]

Interactive computing by <a href="https://jupyter.org/" target="_blank"> <span
style="color:#333399"> Jupyter Notebook </span> </a> &nbsp;|&nbsp;Coded by <a href = "mailto: jmc.xavier@fct.unl.pt">José Xavier</a>

Licensed under  <a href="http://creativecommons.org/licenses/by-sa/4.0/"
target="_blank"> <span style="color:#333399;font-size: 20px"> CC BY-SA 4.0  </span></a>
